### ISSUE TITLE
Doesn't recognize AltGr

### ISSUE THREAD

**Issue by Makere** [randyrants/sharpkeys#1]
In the Swedish/Finnish keyboard, there is AltGr in place of RightAlt, SharpKeys doesn't recognize it (E0_2038).

**Comment by kristofferR** [comment]
Yeah, I were going to create an issue about this too. 

I want to make Shift+4 create a $ (which you type on Norwegian keyboards by AltGr+4) instead of a ¤.

**Comment by randyrants** [comment]
@Makere - AltGr should be in the list, unless Swedish/Finnish keyboards are sending a different key value than the rest of Europe.  Any Alt key has challenges in the TypeKey window because the keystroke gets consumed by Windows, so you have to select it from the list.

@kristofferR - I can save you the time in filing the issue: this cannot be done with SharpKeys.

The Windows technology that is remapping a key remaps the whole key.  There's no way to say Shift+4 does this but 4 does that.  You can remap the 4 but all modifications of that key will go with it (Shift+, Alt+, Ctrl+, AltGr+, Win+).

**Comment by kristofferR** [comment]
Ah, I see. It seems like AltGr+ actually creates new individual keys though, as the key code shown in "Type Key" changes depending on which key is pressed together with it (Just AltGr=E0_2038, AltGr+1=E0_1F02, AltGr+2=E0_1F03 etc).

However, you're right that about Shift though, so I guess I'll try making my own keyboard layout instead. Thanks for the app anyway! :)

**Comment by tmthywynn8** [comment]
Right Alt is E0_38, while AltGr is E0_2038, both according to SharpKeys. I am using the United States-International keyboard layout to reproduce his key.

For Windows 10:
1: Open Settings (Windows+I) --> Time & language --> Region & language.
2. expand the Windows display language"entry, and click on Options.
3. Click on "Add a keyboard."
4. Click on "United States-International."
5. Press CTRL+Shift to switch to the "United States-International" layout.
6. Open SharpKeys, click Add, and then click "Type Key." Press the AltGr key, and you'll see "(E0_2038)" appear.

Is E0_2038 identical to E0_38, then?

**Comment by Makere** [comment]
It seems that if I just use sharpkeys on the RightAlt, it does AltGr.

**Comment by tmthywynn8** [comment]
You are right. I just tried it just now. I just thought that since the scancodes (is that the right term?) were different, it couldn't possibly work, but it does. I apologize for my assumption.
