### ISSUE TITLE
Last windows update, stopped working

### ISSUE THREAD

**Issue by eamania** [randyrants/sharpkeys#100]
Hi, I have a problem, I've been using SharpKeys in a notebook for a few weeks. Since the last windows update it has stopped working.
All the mappings I had no longer work. I tried reinstalling sharpkey and re-mapping but no results.
I'm desperate, in the notebook I miss the keys <> (E0_56 in the Italian layout), I remap in the F12 key (E0_58) but now it does not work anymore :(
Thank you

*sorry for my not good English

**Comment by randyrants** [comment]
Not entirely sure what I can do this as I've been running on the RS4 release of Windows for months and everything is still remapped.  Reinstalling SharpKeys won't help because all of the content is stored in the registry and SharpKeys doesn't do any of the remapping.  Recommend that you remove all of the mappings, save, reboot, put back your mappings, save, and reboot again.  HTH!
