### ISSUE TITLE
sharpkeys windows/cntrl keys no effect in game program

### ISSUE THREAD

**Issue by unLvcky** [randyrants/sharpkeys#102]
Hi, I have an Issue when I run a program (LeagueOfLegends Game) the remaped windows/Cntrl keys does not take effect in the Game. Can this be solved?

**Comment by randyrants** [comment]
Games have always been tricky because some games are handling keyboard codes on their own and others are getting input directed from Windows.  Can't speak for League of Legends but I think that under DoTA SharpKeys can remap the keyboard.  You might want to look into something like AutoHotKeys or in the League's setting as well as there is often something the game can do to help.
