### ISSUE TITLE
Is it possible to add FN remap support for "Microsoft Wedge Mobile Keyboard"?

### ISSUE THREAD

**Issue by 9527KKK** [randyrants/sharpkeys#107]
Is it possible to add FN remap support for "Microsoft Wedge Mobile Keyboard"? 

https://www.amazon.com/Microsoft-U6R-00001-Wedge-Mobile-Keyboard/dp/B008OEHPKM

Latest version still does not support FN remap. 

Thanks.

**Comment by 9527KKK** [comment]
I took a deep look. I notice this code
        public bool PreFilterMessage(ref Message m)
        {
            if (m.Msg == 0x100) //0x100 == WM_KEYDOWN
                ShowKeyCode((int)m.LParam);
            // always return false because we're just watching messages; not
            // trapping them - this message comes from IMessageFilter!
            return false;
        }

However, on that keyboard, if you press f3 (vol down) or f4 (vol up), LParam are the same. The diff is WParam. F3 is 174. F4 is 175. Seems current code does not handle this case.

**Comment by 9527KKK** [comment]
Moreover, when pressing f6 (marked as "shared" button), WM_SYSKEYDOWN is triggered instead of WM_KEYDOWN.
May you please add support for these corner cases?

**Comment by randyrants** [comment]
Fn isn't purposefully unsupported - the problem is that every keyboard treats it different and there's no way to successfully map it.  Further, the Fn key is often trapped by the driver triggering a different Windows message.  Given that the Registry key that SharpKey points to does remap WM_SYSKEYDOWN, I don't think there's anything to be done here.

You might want to try AutoHotKeys which is a more active remapper.
