### ISSUE TITLE
Failure to map or undo mapping on Dell laptop

### ISSUE THREAD

**Issue by sharptrees** [randyrants/sharpkeys#11]
@randyrants 

Win 10 - Dell inspiron 7000 - Dell laptops often don't have an 'Application Key' (Near Right Ctrl Key). However the key is accessible as standard on many Dell laptops via Fn+RightCtrlKey

As a heavy keyboard user I assumed Sharpkeys would be ideal to use on my (new) laptop to change the RightCtrlKey (E0_1D) *to* the 'Special: Application' Key (E0_5D)

This didn't work, and I now have *no* Application key whatsoever (not even Fn+RightCtrl)

I deleted the mapping in SharpKeys as suggested but to no avail.

I then tried creating a reverse mapping E0_5D to E0_1D - Nothing

My RightCtrl works, my Fn works (thank god)

Fn+RightCtrl = Nothing (No Application Key)

I don't understand why SK failed the original mapping and wont undo the damage when the mapping is removed / deleted with SK (ie: permanently disabled Application Key via Fn)

This must be a bug I assume?

Many thanks for any advice helping me get on of my favorite keys back!

**Comment by randyrants** [comment]
I cannot speak to anything going on Fn+ anything since that's going to send keys that may or may not get to Windows.  That said, on my Lenovo, I've remapped the Right Alt key to Application (and Right Ctrl key to Left Windows).  Which version of Windows are you running?

**Comment by sharptrees** [comment]
Win 10

Sharpkeys listed 'Special: Application' Key (E0_5D)

and listed RightCtrlKey (E0_1D)

I used sharp keys to map the former (listed in SK as Special: Application' Key (E0_5D)) which it found in Windows, to the latter: RightCtrl

**Comment by randyrants** [comment]
Sorry, I meant which build of Windows: ver from a command prompt.

And yes, Application is a standards Windows key, introduced with Windows 95 and is often left off on laptops, which is why I know what it is and that it can used in a mapping as I have done it myself :)

**Comment by sharptrees** [comment]
Version	10.0.14393 Build 14393

Sorry about the confusion re: the application key.. I must have misunderstood what you meant when you were referring to the mapping of the application key selected from the list 'Special: Application (E5_0D)' "may or may not getting to windows"?  

I don't understand what you mean by this Application key "not getting to Windows" as the operating system is Windows which obviously handles the Key by design in general and one would assume "gets to Windows" by design via Fn keys which countless Windows machines support including all the Dells like mine which successfully have been using Fn to access standard Windows functions for many years.

Sorry that I don't understand, could you please explain because it might help me regain my windows Application function which I had via my keyboard native on my Dell before making a mapping in Sharpkeys

**Comment by randyrants** [comment]
So that's Anniversary Edition which has no known issues; some people in other threads have mentioned new behavior in Creator Editor so I wanted to clear that up first.

First and foremost, SharpKeys doesn't do any of the remapping: it sets/reads from a Registry key.  Windows does all of the remapping based off scancodes that are on the Registry value.  There are some keys that hardware traps on its own and doesn't pass it back to Windows.  Fn, Media, or Power keys as examples: sometimes Windows gets told they were press and sometimes they don't.

If you want to get back to your original state, run SharpKeys, delete all of the remapping entries, save those changes, and reboot.  That will remove all of the entries in the Registry and you should be in your original state.

**Comment by sharptrees** [comment]
> If you want to get back to your original state, run SharpKeys, delete all of the remapping entries, save those changes, and reboot. That will remove all of the entries in the Registry and you should be in your original state.

As stated in my original post this was the first thing I tried to rectify the situation, and a signal there must be some kind of bug with SharpKeys or incompatibility with Dell laptops

**Comment by randyrants** [comment]
Right, so, again: SharpKeys is not remapping anything: it's tweaking a Registry key.  It has also been around since 2004, so I can honestly say that it work with Dell laptops because there would have been 13 years of bug reports if it didn't work with Dell.

If you deleted all of the entries, saved, and rebooted (because if you don't reboot, the setting doesn't change) then the last thing I can offer is deleting the Registry key by hand:
- Open regedit
- Go to Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout
- Select the Scancode Map value on the right
- Delete the value
- Reboot

That should return you to your original state.
