### ISSUE TITLE
Can't remap key 'E0_1F6C' on Surface Bluetooth Keyboard

### ISSUE THREAD

**Issue by whistlerpro** [randyrants/sharpkeys#120]
Hi, great program. I have one problematic key on the row of special keys above the numpad of the Surface Bluetooth Keyboard. It's the one that looks like it should activate the notifications panel on Windows 10, but in my case doesn't do anything - hence the desire to remap to something. 

But SharpKeys doesn't recognise them, is there any possibility this can be fixed?

This is the case for the whole row, which comes up with the following codes:

Calculator [shows as '(00_0100)']
View Desktop [shows as '(E0-5B) - Special: Left Windows']
Notifications? [shows as '(E0_1F6C)']
Lock screen [shows as '(E0-5B) - Special: Left Windows']

I notice two of the special keys are shown with the same code and description, which can't be right. I can't explain that one!

**Comment by randyrants** [comment]
I have a solid guess as to what is going on: the Surface driver is intercepting these key presses and doing something special to them and then passing them on to Windows as something that it can ignore.  I have the natural version of the Surface keyboard and I've left these keys unmapped because Windows isn't getting good information about them.  I pressed the Lock key with the hope of making that scancode available for every other keyboard but that's another that comes back as Left Windows.

Sadly, it means there's nothing SharpKeys can do with these keys.
