### ISSUE TITLE
HP ZBook G5 unknown keys

### ISSUE THREAD

**Issue by Troi7** [randyrants/sharpkeys#121]
Hi, my new notebook has 3 useless keys. It would be great if I could remap them, at least F15 to Insert). These 3 keys are unrecognized by SharpKeys now:
E0_1F6D (F13 - share screen)
??? (F14 - pick up phone) - type key did nothing
E0_1F65 (F15 - hang up phone)
Thanks

**Comment by aarnej** [comment]
My new HP Elitebook 840 G5 has the same issue. The keycodes reported by SharpKeys are same as above.
(BTW, the Insert key on this keyboard is factorymapped to Fn-E. Shift-Insert can be entered by pressing Shift-Fn-E, _but only when keys are pressed in that order_. That is, Fn-Shift-E won't work because it toggles the Fn lock)

**Comment by randyrants** [comment]
Sadly, there's nothing that can happen here. F13, F14, and F15 already have scancodes that Windows responds to and it appears that the keys HP is calling F13-F15 are not the same.  Since this app only exposes a Registry key that Windows uses to make the remapping, there's not much to happen here.  

You might want to try a more active remapper like AutoHotKeys.

**Comment by xor2003** [comment]
Actually the codes are:
E0_1F6D (share screen)
??? (F14 - pick up phone)
E0_1F65 (hang up phone)

And SharpKeys saying it does not know about those two, please update.
Could you support those two?

**Comment by randyrants** [comment]
Nope.  These are triple byte codes which cannot be remapped by Windows.  You might want to try the remapper called out above: AutoHotKeys.
