### ISSUE TITLE
support for key with code E0_1F6D

### ISSUE THREAD

**Issue by tjuhasz1** [randyrants/sharpkeys#137]
Hi, could you make SharpKeys support the key with code E0_1F6D? My new HP laptop does not have an insert key, and there is a special key (with an icon of a monitor on it) which I could use for insert function. Unfortunately this is the only key which’s original function I won’t miss later. Regards: Tamas

**Comment by randyrants** [comment]
It's already checked in, awaiting a new release.

**Comment by theoneandonly-vector** [comment]
this still doesn't work on latest release.

**Comment by randyrants** [comment]
Actually, it checked in and then I ripped it out a few weeks later.  In spite of users testing it can confirming it worked for them, I verified that the Registry key that Windows is using to remap the key cannot support triple byte keys.  Because of this there's no reason to have the keys available and I've removed them.

You might want to try a more active remapper like AutoHotKeys.
