### ISSUE TITLE
Computer crashes

### ISSUE THREAD

**Issue by deadmcslave** [randyrants/sharpkeys#156]
Hello, since I got this program to disable my F1 key on 2 days time I've gotten 2 bluescreens and another weird thing happen to my computer where I had to restart it for can't describe it since it was so rare. Anyways the reason why I disabled my F1 key is because like half a year ago I spilled some beverage over my keyboard and I cleaned it, cleaned it from the inside and for some reason my keyboard thinks the F1 button is pressed down while its not. Even after opening up my keyboard I can confirm from the inside its not pressed down either. So I downloaded some program that disabled my F1 key but it was only working for like 30 days and it was all fine, I used to set my date back to before it expired so I could keep using it but it's really annoying to do that every time you start up your pc. Few days ago I found this program, I really like it besides that my pc got a bluescreen twice since I got it and other stuff happened. All I did was disable the F1 key and wrote it to the registry. Maybe I'm having these issues because my keyboard still sends out F1 but my pc needs to constantly ignore it/block it? I need some help over here..

**Comment by randyrants** [comment]
There's nothing that SharpKeys could do that would cause a blue screen crash.  If you are concerned that the remapping is causing some sort of problem, remove all the mappings and reboot.  If you think that the blue screen is from F1 being sent to your PC from a shorting keyboard, it's more likely the shorting keyboard is causing the BSoD rather than the F1's.  Might want to get some fresh hardware.
