### ISSUE TITLE
Unknown key: (00_100)

### ISSUE THREAD

**Issue by AndrewMcClelland** [randyrants/sharpkeys#164]
On the IKBC MF108 v.2, there is a "CAL" key on top right corner. It currently opens the calculator which I'd like to remap :)

**Comment by randyrants** [comment]
00_100 is a generic scancode that Windows reports when it doesn't know the scancode, typically because the key is interpreted by hardware (e.g. Volume) or is intercepted before Windows gets it, which is likely the case here.

Sorry it cannot be of more help!

**Comment by rekliner** [comment]
It might be worth mentioning in the dialog box rather than "You've entered a key that sharp keys doesn't know about"...something along the lines of "this may be a special hardware key that sharp keys can't access".

In my case it is a bluetooth camera shutter button that for all intensive purposes is a standard bluetooth keyboard with one button.  Oddly, even using generic bluetooth keyboard driver it turns media volume up, though I am able to remap my main keyboard's media volume up button...i wonder how different can they be.  https://www.amazon.com/gp/product/B07BLWY9BP/
