### ISSUE TITLE
sharpkeys not remapping my keys

### ISSUE THREAD

**Issue by Suhail** [randyrants/sharpkeys#166]
Here's a screenshot: http://prntscr.com/mny7rl

I rebooted several times & clicked "write to registry"

Here's my OS information:
OS Name:                   Microsoft Windows Server 2016 Datacenter
OS Version:                10.0.14393 N/A Build 14393

I am using an Apple keyboard.

**Comment by randyrants** [comment]
Is the Command key being recognized as a Windows key?  If so, see if you can turn the key off entirely.  I'm worried that there might be a Group Policy in place - Server and Datacenter in particular - that turned off the remapping that Windows usually does.  Would make sense since if you remap a key that you used for a password, you'd be in a world of hurt on a Server instance.

**Comment by Suhail** [comment]
I tried turning it off via this: http://prntscr.com/moblg2 but it didn't work

Any ideas on how to change the group policy or debug the issue?

**Comment by randyrants** [comment]
For Datacenter?  Not a clue.  I mean there's the Group Policy Manager but I have no idea if there's a specific policy that covers this or if it's just completely locked down.  The last time I ran Server (which was almost a decade ago) there were a ton of services shut down, which is why I first started thinking this.  The only other troubleshooting thing to try is plugging in a PC keyboard and see if the Windows key is in fact still enabled with the above settings.

**Comment by thuhreb** [comment]
When you map your keys, instead of selecting the key via the scroll list, use the type key button if you haven't tried already.  Once you type the key and click OK, the application will throw an error if you entered a key it doesn't know about.  So for instance, letter "b" on your keyboard might not be presenting itself and a general letter "b".  I just ran into that with my keyboard for volume commands.  I feel that it has to do with software running or particular drivers supporting certain model keyboards that allow certain keys to transparently seem standard but are not.
