### ISSUE TITLE
Per-User Keymapping

### ISSUE THREAD

**Issue by acook** [randyrants/sharpkeys#170]
A lot of corporate machines lock down admin access so keymapping using this method isn't possible. However I ran across a blog talking about an alternative which only makes changes on a per-user basis. This seems like it could be ideal in general so that different users could have different mappings anyway.

https://dropline.net/2009/05/mapping-caps-lock-to-control-without-admin-access/

**Comment by randyrants** [comment]
The only downside is that it doesn't work.  I know because this has come up (via my blog) every year or so.  I always take a look but it never works.

I just did some exporting of my existing Scancode values on the HKLM key.  For me, I disable Caps Lock and remap my Right CTRL key to be a Windows key.  I took the REG file and edited it to be HKCU then deleted the HKLM so there would be no conflict and rebooted.  After the reboot, my Caps Lock key was still active and my Right CTRL does not act like a Windows key.

So while you can add the key, Windows doesn't seem to respect it.

**Comment by EurekaIgnem** [comment]
different thread.  to much of a Barney to start new thread.  I assigned F7 to my F2 key, when I wanted to do the opposite.  How do I get my original functioning F2 key restored?  I tried deleting the keyboard drivers, and tried restoring the BIOS.  Neither worked.   I might be out ... a useful key.   Dell Inspiron 5570 -  And Dell is yet to respond to my question.

**Comment by acook** [comment]
Thanks @randyrants, I can confirm that it doesn't work on my Windows 10 build 16299 system either. Apologies for wasting your time. I'm using https://github.com/susam/uncap in the meantime, but it feels pretty retro to have a TSR commandline program to solve a problem like this. If I run across something else that works I will let you know.

**Comment by randyrants** [comment]
Not a waste: you never know when the Windows tech may change build to build. I also recommend AutoHotKey, which I think is more active, much like the TSR you found.  Cheers!
