### ISSUE TITLE
Apple Magic Keyboard 2 fn keys  can be remapped  in current Windows 10?

### ISSUE THREAD

**Issue by antitodo123456** [randyrants/sharpkeys#172]
Apple Magic Keyboard 2 fn keys (Volume up, Pause, Next)  can be remapped  in current Windows 10? with sharpkeys?

**Comment by randyrants** [comment]
Never tried, honestly.  Media keys can be quiry sometimes, in that they take a different route than usual keys do and therefore don't get remapped.

**Comment by antitodo123456** [comment]
Thanks for your prompt reply. Well this and other wireless Apple keyboards, are objects of desire for many windows users. Mine, (bluetooth with separate numerical keypad) is a very flat one and keys are very responsive, but secure, do not need a lot pf pressure, thus I like it more than a Microsoft alternative, not many others exist or can compare. That said, I have seen (old) videos on Youtube where using Bootcamp drivers, volume up/down worked as well as other FN keys. I have been unsuccessful with latest ones despite some directions from Apple groups. Even some (most)  F keys, e.g. F7  do not work in Adobe apps! I know there is a paid app (SmartKeys ?) that claims to do the trick, but I would like to find an straight solution. And I ask if Apple could include a .inf or .sys file that offers full compatibility for use on a PC with Windows 10.

**Comment by randyrants** [comment]
Honestly, for Bootcamp, Apple has really done the bare minimum for KM support in Windows.  I remember when the MacBooks started to support multi-finger taps/motions yet when I went to Windows, it was one or two fingers at the most.  Many years later, it's the same news eventhough Windows 10 itself has support for three and four finger motion input.  I expect the same was true for Keyboard but I never ran into many issues while in Bootcamp, but that could also be because I didn't do much at the time.

Sorry I couldn't be of more help!
