### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by Pyrobeef** [randyrants/sharpkeys#177]
No keys work for me, I have tried q to y, y to q, shift to q, cap lock to y, and not even in chrome it works. I need help

**Comment by jordanbaron** [comment]
Did you restart your computer after changing them?

**Comment by randyrants** [comment]
Did you save them before restarting?

Also these changes span the entire PC, so it's going to work everywhere or no where.

**Comment by Aragorn2121** [comment]
I have an HP Pavilion dv6780se notebook Win 8.1. I use screenshots a lot. The Function key is on the bottom left of the keyboard and the screenshot key is on the upper right. I need to make them closer so I can get screenshots with one hand. The key shows up as Special: Insert (E0_52). I tried to remap it to F3. Wrote to Registry and rebooted. It remained unchanged.  The Function key itself isn't recognized on the Type Key option.
I want to remap Function + Special: Insert (E0_52) to Function + F3. Is this possible?

**Comment by randyrants** [comment]
Fn by itself is often ignored because it's often a hardware key; when used injunction with another key, it may or may not be remappable: it depends on what the new value of Fn+F3 is.  For example, on my Lenovo, Fn+F3 is Volume Up which is in fact it's own key, but something like Shift+2 is *not* remappable because Shift+2 doesn't map to a new key.  My usual advice is you can only remap the whole key, but Fn makes this "tricky".  That said, without knowing what Fn+Insert maps to, I have no idea if this mapping is possible, but you can always try to remap the key that results in holding down the Fn key - just be careful that you don't remap a key that you require for your sign in password as that will lock you out.
