### ISSUE TITLE
Not runnable on Windows 10

### ISSUE THREAD

**Issue by JimC86** [randyrants/sharpkeys#18]
I have Windows 10, and just want my media button to play Winamp instead of their "Groove Music" (it's worse that WMP...). 
Anyway this is what I get when I unzip the file, and none of them are executables for me... the "manifest" file is "SharpKey.exe.MANIFEST"  I've never really come across that before.
I read it IS compatible with Windows 10 correct? What am I doing wrong? Is there any more information you guys need?
Any help is appreciated.

![image](https://user-images.githubusercontent.com/15162006/27327113-5898e6fa-5562-11e7-9051-6c8f0ec21561.png)

**Comment by randyrants** [comment]
@JimC86 - looks like you got a copy of the source code, which does not include anything that's compiled.  You'll want one of the packages from here: https://github.com/randyrants/sharpkeys/releases

That said, what you want to do is not possible with SharpKeys: this app exposes a registry key that remaps keys rather than something that can trigger a specific application or run a macro for you.  You might want to look into something like AutoHotKeys which does more than key remapping.

**Comment by JimC86** [comment]
Ok thanks.. ive tried Sharp keys and another one that was able to identify
the media button but wouldn't let me choose what it does other than what
other keys already do(which it sounds like is the same deal w sharp keys
unless I misunderstand).
Thanks So much does the recommendation!


On Jun 20, 2017 8:41 AM, "Randy" <notifications@github.com> wrote:

@JimC86 <https://github.com/jimc86> - looks like you got a copy of the
source code, which does not include anything that's compiled. You'll want
one of the packages from here: https://github.com/randyrants/
sharpkeys/releases

That said, what you want to do is not possible with SharpKeys: this app
exposes a registry key that remaps keys rather than something that can
trigger a specific application or run a macro for you. You might want to
look into something like AutoHotKeys which does more than key remapping.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/randyrants/sharpkeys/issues/18#issuecomment-309799780>,
or mute the thread
