### ISSUE TITLE
Doesnt work on fresh windows install updated to the very latest version.

### ISSUE THREAD

**Issue by AbdoMahfoz** [randyrants/sharpkeys#182]
SharpKeys runs. It detects my key presses. I successfully mapped my keys in the software. It used to work before but after a fresh windows install nothing is changed after restarting. Opening SharpKeys again it knows the mapping that I have made. Clicking write to registry and restarting again does absolutely nothing.
![image](https://user-images.githubusercontent.com/29104356/58024954-a7200780-7b13-11e9-94b2-fe32b9bc775d.png)

**Comment by randyrants** [comment]
And you rebooted?  I've installed 1903 a LOT lately, as fresh installs, and the remapping works as expected.

**Comment by AbdoMahfoz** [comment]
Yes I rebooted multiple times.

**Comment by AbdoMahfoz** [comment]
I dived into the source code, I will check the registry in my pc if keyboard layout is correctly updated, if things went wrong I will break point the method that updates the registry and see what happens
I will keep you posted :D

**Comment by randyrants** [comment]
I can save you time on the source: the only thing SharpKeys does is read and write from a Registry Key - Windows is what is doing the remapping, based off the Key.  So if SharpKeys can still read/write from that Key successfully (which is should be since it's showing you your key) then it's doing what it's supposed to.  

You might want to try clear it all, setting a different key (like Caps Lock), and see what happens.  If that doesn't work, it could be something else is preventing the remapping.  Like on a corporate network, there might be a group policy blocking it unexpectedly.  If I hadn't just re-imaged a box last week and remapped like 10 keys for a Surface keyboard, I wouldn't be a sure that things should still be working...

**Comment by AbdoMahfoz** [comment]
okay :D <3
take a look at my scan code map, i am supposed to be binding the quotes key (00_28) to scroll lock key (00_46) and that's it
is the scan code map correct ?
![image](https://user-images.githubusercontent.com/29104356/58041304-10b20d00-7b38-11e9-8720-a95642b961a4.png)

**Comment by AbdoMahfoz** [comment]
according to the comments in your code the map is correct, so the problem is outside the scope of your software
you can close the issue if you want, i will see why windows ignored the map

**Comment by AbdoMahfoz** [comment]
I reversed the order of the keys in the scancode map and rebooted..... It works now :D

**Comment by AbdoMahfoz** [comment]
![image](https://user-images.githubusercontent.com/29104356/58042552-43a9d000-7b3b-11e9-822d-d89d7003e636.png)

**Comment by randyrants** [comment]
> It works now

Now I can close it! :)

**Comment by AbdoMahfoz** [comment]
if you can test your software on the latest verison of windows, can you please check if it will work? if this something that exists in an updated version of windows I can make a pull request that will reverse the order if the windows version >= my current version
![image](https://user-images.githubusercontent.com/29104356/58042764-cc287080-7b3b-11e9-95d3-5c7882463b3d.png)

**Comment by AbdoMahfoz** [comment]
I was dumb.... I wanted to map scroll key to quotes key... But I told the software to do it the other way around...
I am soo sorry for wasting your time :D

**Comment by randyrants** [comment]
It's all good.  And yes I can confirm that it works on the most recent (18362.113).
