### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by jebeld17** [randyrants/sharpkeys#185]
# SharpKeys is in need of a new, modern icon.

(UPDATE: Please see below, along with Pull Request https://github.com/randyrants/sharpkeys/pull/186)

**Comment by jebeld17** [comment]
I put together a quick addition for the SharpKeys program as a brand new, modern icon, inspired by Fluent Design. Take a look below:
![Icon](https://user-images.githubusercontent.com/9492083/58883947-6c8aa300-86ad-11e9-8083-bab50024c40e.png)

With that, SharpKeys also gets a new logo:
![SharpKeys_Logo](https://user-images.githubusercontent.com/9492083/58883967-76140b00-86ad-11e9-8137-4db61c4d5f65.png)

Other attachments:
[Assets.zip](https://github.com/randyrants/sharpkeys/files/3252688/Assets.zip)

**Comment by jebeld17** [comment]
See Pull Request 186:
https://github.com/randyrants/sharpkeys/pull/186

**Comment by randyrants** [comment]
I had to close the PR because there's no way to make SharpKeys a Microsoft Store app; if you are interested in submitting a new logo, please work it into the Win32 codebase, which I think requires an ICO file.

Thanks!

**Comment by jebeld17** [comment]
My Pull Request did so and swapped out the .ICO file.
In addition, Microsoft now allows full-privileged Desktop Apps into the Microsoft Store.

**Comment by jebeld17** [comment]
See Pull Request https://github.com/randyrants/sharpkeys/pull/187

**Comment by randyrants** [comment]
The last meeting I went for this called out that while Win32 apps were supported there were still restrictions in place to protect critical parts of the system which included HKLM.  I'll ask around on campus and see if that's still the case and check WACK.  I started trying to get this into the Store 18 months ago, so it's not because I don't want it - it's because it wasn't supported.

**Comment by randyrants** [comment]
Sadly, the policy is unchanged: https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-prepare

These three in particular:
- **Your application always runs with elevated security privileges.** - SharpKeys has to elevate itself to write to the Registry Key that Windows uses to remap things.
- **Your application modifies the HKEY_LOCAL_MACHINE (HKLM) registry hive.** - SharpKeys has to write to this hive because Windows does not respect any remapped keys when written to HKCU.  It's been tried: doesn't work.
- **Your application writes to the AppData folder or to the registry with the intention of sharing data with another app.** - while SharpKeys isn't trying to put content in the Registry to share the data with other apps, Windows still needs to find the Value and there's no way it's looking in AppData.

Unless there's something that changed with VS 2019, this is the most recent information out there.
