### ISSUE TITLE
Question about sharpkeys capabilities

### ISSUE THREAD

**Issue by ghost** [randyrants/sharpkeys#19]
I purchased a Lenovo 910 and found the shift key to be too far to the right.  Wanted to remap.  Found this blog on the internet:

II. Right Shift Key - an incredible poor design by Lenovo. Hopefully the engineers are reading the forums.
 
I tried to retrain myself to use this poor keys placement design, but jumping back & forth between my work station and Yoga, it was impossible. My already slow typing slowed to crawl. I was ready to throw the Yoga in the trash. But a big thanks to forum members PaulProe and 90c4 who saved my Yoga's life.
 
I remapped:
Right shift to Page Up
Page Up to Right Shift
Page Down to Right Direction
Right Direction to Page Down
 
Download and run http://sharpkeys.codeplex.com/

But intro to sharpkeys states that you cannot swap keys, which is what seems to have been done here. Can sharpkeys be used to make the changes described above?  Thanks

**Comment by randyrants** [comment]
Mostly because a number of people have found that if they remap Shift to Page Up and Page Up to Shift, they end up with two shift keys or two page up keys.  Assuming that neither key was required for typing in your sign in password, it's worth a try.  The biggest issue people have with trying something like this is they aren't able to type in their password because the keys are unavailable.

**Comment by osearth** [comment]
I eoulduse accessability On screen KB, then thought it mught remap keys on there too. Could apossibly use the olddos trick for special chars hold ALT and press some Numpad keys. IE <ALT>+333 outputs uppercase M. Could be a useful way to type passwords if you have the right character codes.
