### ISSUE TITLE
SharpKeys seems to conflict with Surface pen shortcuts

### ISSUE THREAD

**Issue by junfengy** [randyrants/sharpkeys#191]
First of all, thanks much for creating such an excellent utility!

I noticed that after I remap keys using SharpKeys, my Surface Pen shortcut button stops working.  If I clear all the remap entries, my Surface Pen shortcut button begins working again.  

I'm using Windows 10 version 1903, Surface Pro 6, and Surface Pen 2017.  Enclosed is the keys I remapped:

![image](https://user-images.githubusercontent.com/3514460/59635507-61a92700-911f-11e9-89d0-800c16ea2273.png)

Thank you!

**Comment by randyrants** [comment]
Hi - interestingly, I have almost the same config available for testing: 1903, Pro 6, but with a pen from 2018.  That said, I also have remapped F9-F12 to Home/End/Page Up/Page Down and Home/End/Page Up/Page Down to F9-F12 along with Caps Lock disabled and Right Alt to Left Windows.  When I press the pen button, I get screen clipping.

Do you see anything when you click the button?

**Comment by junfengy** [comment]
When I click the button (single click, double click, long click), nothing shows up if the remappings are written to Registry.  If I restore the original mappings, then all three ways of click work well.

Is there any more debug information I can provide?

To be clear, I bought my Surface Pen recently and it is the 4th gen model released in 2017.  I think your surface pen should also be the 2017 4th gen version. (https://en.wikipedia.org/wiki/Surface_Pen)

**Comment by randyrants** [comment]
I have 5th in that I have no clip.  Let me clear my settings, set these and reboot to see what happens.  Since my app doesn't do any of the remapping - Windows is doing all the work - but it could be that the remapping is knocking out the pen handler.  If that's the case I doubt there's anything that can be done for it.

**Comment by junfengy** [comment]
Thanks Randy!  My pen has no clip, either, so yours and mine should be the same gen. I'm using the default pen&ink config:

![image](https://user-images.githubusercontent.com/3514460/59639035-016ab300-9128-11e9-8d84-44de80df6b57.png)

If the pen button works in your setup, it should not be that the remapping is knocking out the pen handler though?

**Comment by randyrants** [comment]
Confirmed that the same behavior is occurring!  That's good because it means we're both sane.  Let me unload each key one by one to see what is borking, just so we know what the combination is.

**Comment by randyrants** [comment]
Left Windows to Left Alt is borking it!  No idea why - could be the Surface driver is using Win+somekey to trigger the clipping app to open.

**Comment by randyrants** [comment]
Just checked: snip and sketch is wired to respond to Shift+Win+S - I'm guessing that it's attempting to send keyboard commands and for some reason the key stroke is getting eaten.

Sadly, there's nothing that I can do to fix this as it's all being done by Windows, in layers below my control.

**Comment by junfengy** [comment]
Thanks for the speedy debugging anyway, Randy!  I'll see if I can file a bug report to Microsoft.

**Comment by FishBoyBlue** [comment]
I think I figured it out!!!
Specifically windows is triggering the LEFT windows key when the surface pen shortcut (eraser) button is pressed. I was running into this issue for a very long time, and after reading this forum I figured why not try Right Windows key since there is no right win key on any of the surface keyboards. And to my absolute astonishment its working!!

While I have a surface book, I really liked the placement of the command key on apple keyboards, so I use one as my daily driver. Having to remap the Win key to CTRL is a necessity to make that keyboard usable. However, while using the MS keyboard, the Win Key is in just the right spot to thumb Command/Ctrl. I resigned the keys, and set my right click button as Left Windows Key.

But TLDR, its the Right windows key you should try resigning!
Hope it helps!

**Comment by kolaveridi** [comment]
@randyrants I think, pen button is being recognized as left windows key. It is happening only on Sharpkeys or whole Windows in general, I'm not sure. Btw I'm looking to use pen button as scroll, for which I have to use it as a space button or as down arrow key (small scroll; not preferred). Presently, I can't do so bcz Windows key is crucial for daily use and can't overwrite it (or even repurpose it to a different key out of habit). Please look into this. It would be of great help if you could:

1. Reassign to pen button to some Special/Unknown Key.
2. Design keys specifically for large scrolls (I know this is a big ask and don't even know if it is possible. You can simply ignore it if you think this would be a nightmare task),

**Comment by randyrants** [comment]
The pen's buttons do not go through the keyboard input method, even if it does throw a random Windows key into Type Key: I think that's a side effect of what the pen software is doing behind the scenes.  In Windows 11, when you activate the pen, it brings up the "ink workspace" which is now a toolbar that pops up and pressing the button opens whiteboard.  In so far as I know, there's not keyboard combination to trigger any of this, especially since [if it's still true] the ink apps had to be protocol activated.
