### ISSUE TITLE
Keys not swapping

### ISSUE THREAD

**Issue by squirfle** [randyrants/sharpkeys#197]
Hello. I tried swapping Capslock ( Special 00_3A) to Backspace ( Special 00_0E). After reboot both Capslock and Backspace behave like Backspace.

**Comment by randyrants** [comment]
Can you post a screenshot of what is remapped.  I used to call out that swapping keys didn't work, because of reports like these, but then other people say it works fine.

**Comment by squirfle** [comment]
![sharpkeys](https://user-images.githubusercontent.com/53276601/62033913-ae3f5200-b1f5-11e9-9d4f-4f759407ca1d.png)

**Comment by randyrants** [comment]
Well the good news is that based off what I see, the remapping is what you want it to be: you've told Caps Lock to be remapped as the Backspace key.  What functionality were you looking for?

FWIW, when you're remapping a key, you can always think of the right as the "new key" which is why there is a "Turn off Key" option at the top of the list.

**Comment by squirfle** [comment]
I just realized that in order for the keys to swap, I need to change from caps lock to backspace and then backspace to caps lock. So dumb of me. I did it and in windows it works fine so far, however when I tried binding something to my new backspace (old capslock) in a game doesn't realy work as it should. I tried binding the quest menu in Witcher 3, but in order for the menu to stay up I have to keep the key pressed whereas if I were to bind it to any other key I would only have to press it once and the quest menu appears and stays up until i press the key again when it closes.

**Comment by randyrants** [comment]
My guess is that Caps Lock has a sort of stateness about it within the hardware.  Like normally, it acts like a toggle switch rather than a regular key.  I would imagine if you mapped it to Scroll Lock or Number Lock you would see the same behavior.  At least that's my guess.  My app just manages the Registry Key that Windows uses to remap the key.
