### ISSUE TITLE
Cannot remap keys after reboot computer (Win 10 Pro)

### ISSUE THREAD

**Issue by fktuen** [randyrants/sharpkeys#199]
Sharpkeys worked perfectly for a couple of days until I restarted my computer (rebooting) under Win 10 pro OS. Same issue happened to other keyboard remaping apps.

Anyone having the same issue and would know how to fix it? Much appreciate.

**Comment by randyrants** [comment]
I have not seen this, especially since you have to reboot for the Registry setting to kick in.

After you reboot, can you check SharpKeys again and see if your remappings are still there?  It could be that some other program (from an IT dept or security app) might be wiping the remapped keys which would explain quite a bit.
