### ISSUE TITLE
Allow multiple keys selection at the same time

### ISSUE THREAD

**Issue by kingio** [randyrants/sharpkeys#20]
Hi & ty for creating this piece of software!

I'm preparing my computer to show a Google Chrome in kiosk mode, so i need to block almost any key that its not in A-Ba-b.
As SharpKeys doesn't allow multiple selection, it forces me to click one by one key to set them to do nothing.
¿Couldn't it be possible to select multiple keys (not combo)?

Second question is: 
**O.S**: Win 10
**Keyboard layout**: QWERTY - spanish
(https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/KB_Spanish.svg/420px-KB_Spanish.svg.png)
When i press some keys like Left Win, or any Alt, SharpKeys says that he doesn't know about that key (but it is able to detect it). In what matters that is not listed in Key Mapping if it is able to recognize it anyway? 
¿Couldn't that be possible to just list it as "Unknown"? In Key Mapping there is already a big amount of "Unknown" keys :S

**Comment by randyrants** [comment]
@kingio hi!

On the first question, yes, you can turn off the whole keyboard but I warn you: you will likely not be able to sign into the box if you do this.  The remapping starts at boot time through shut down and you have to reboot for the key remappings to take effect.  You are very likely to lock yourself out of the box and I cannot help you get back in.  That said, I would recommend getting a Kiosk software solution in place rather than using this.

On the second question, Alt is never recognized by TypeKey: you have to select it from the list.  For the Windows key, it should have been recognized but I have no knowledge of the Spanish keyboard you're using so I cannot confirm that.  You can always select the Windows keys like the Alt keys, in the list.

HTH!
