### ISSUE TITLE
Problem remapping NumLk

### ISSUE THREAD

**Issue by EnnexMB** [randyrants/sharpkeys#205]
I have been making keystroke errors on my new computer, so I wanted to move the NumLk key and the numeric keypad "."/delete to different locations, as well as disabling two other keys. In SharpKeys, I did not select the keys from the list, but typed both From and To keys on my keyboard. The resulting SharpKeys window looks like this:

`From:...................To:`
`Num: - (00_4A)..........-- Turn Key Off (00_00)`
`Num: * (00_37)..........Special: € (EO_45)`
`Num: . (00_53)..........-- Turn Key Off (00_00)`
`Num: / (E0_35)..........Num: . (00_53)`
`Num: + (00_4E)..........-- Turn Key Off (00_00)`
`Special: € (EO_45)......-- Turn Key Off (00_00)`

And here is the skl file made from that: [remap Asus num pad.skl.txt](https://github.com/randyrants/sharpkeys/files/3610154/remap.Asus.num.pad.skl.txt) (with ".txt" appended to the filename to allow GitHub to upload it).

The "Special" key with the euro symbol is what I got from pressing the NumLk key.

The results of this are:

- The "."/delete, "+", and "-" keys are correctly turned off.
- The "/" key now behaves correctly as "."/delete.
- But NumLk still works as NumLk.
- And "*" does not do anything, as if it's turned off.

I have two questions:

- Can someone see a reason that the remapping of the NumLk key did not work and tell me how to get it to work?
- Is there a way to get an exact record of the changes that the above list made in my registry, so I can look in the registry myself and see what's there? I exported the whole registry to a file before doing this, so if I knew all the registry keys that SharpKeys changed, I could open the old registry in NotePad++ and compare the old values with the new values in the current registry.

Thanks for your help.

**Comment by EnnexMB** [comment]
Update: I had the idea to test what happened to the NumLk and `*` keys by going to "SharpKeys > Add > Type Key" and pressing those two keys. What I got was the same result for both keys: They both report being "Special: € (EO_45)". However, in terms of behavior, they are different. As I said before, the NumLk key continues to do its NumLk job of toggling the numeric keypad between numbers and cursor movements, while the `*` key does not seem to do anything.

So the mystery remains. Looking forward to your insights.

**Comment by EnnexMB** [comment]
Update #2: I've made a map of my entire keyboard, showing the scan code for each key, using the "Type Key" tool in SharpKeys. Here is the map: 
[keyboard scancodes.pdf](https://github.com/randyrants/sharpkeys/files/3613479/keyboard.scancodes.pdf)

There is an interesting surprise from that exercise that might be related to the my problem moving the NumLk key. When I press the Pause key in "Type Key", the result is "Special: Num Lock (00_45)". So it seems that SharpKeys (and maybe therefore the registry) thinks that my Pause key is the NumLk key and it thinks my NumLk key is the euro key. I've never used the Pause key and I don't know what it does. I just now pressed it and it doesn't toggle the behavior of the numeric keypad, so it is not acting as a NumLk key.

Does this offer any clue of what is going on with my NumLk key and how I might be able to move it to the NumPad "*" key?

**Comment by randyrants** [comment]
Thanks for investigating this to this level but TL;DR is what you have is what you have.

Some keys on keyboards are not wired as they "should" be.  Sometimes it means that the hardware is intercepting the scancode; sometimes the scancode comes back as some generic 00_100 for multiple keys.  This is not uncommon in hardware or services: there are lots of examples where a TV will report that it's able to support things that it cannot down an HDMI wire and web servers that say "I can take any type of input!" but when you send them a specific HTTP command, they crash.

This feels like one of those times.  Type a Key is simply reporting what Windows sees the key as.  If NumLock is reporting a Euro key, it could be that you are using an en-US keyboard but Windows might be expecting en-GB.  Or that the hardware is misrepresenting the key.  Or there's some driver in the middle and it's throwing up a different key.  My advice would be to forget Type a Key and try selecting the NumLock out of the list on the left of the UI.  If this works, you've got what you need.  If it doesn't work (and the wrong key gets remapped) then this Registry hack will not work no matter what you do because even if you build the Registry value by hand, the same issue will be present.

HTH!
