### ISSUE TITLE
Remapping Numpad Issue

### ISSUE THREAD

**Issue by SciencePiggy** [randyrants/sharpkeys#206]
I recently bought a laptop and am frustrated by the Home/End keys being buried under Fn keys. I was hoping to map them to keys on the numpad that have no function while NumLock is off. Unfortunately while the SharpKeys "Type Key" feature detects the keys while NumLock is on (e.g. Num: 7 (00_47)) it does not register the key press with NumLock off.

To clarify. My numpad 7 doesn't return a result as opposed to my media keys (also located on the numpad), which return 00_100.

Am I out of luck?

**Comment by EnnexMB** [comment]
Interesting coincidence that you post this issue a day after [my issue](https://github.com/randyrants/sharpkeys/issues/205) about remapping the numpad.

Also interesting that our numpads appear to behave differently. On my computer, in SharpKeys with numpad doing numbers, if I do Type Key on numpad 7, I get "Num: 7 (00_47)". If I then switch to a different Window, press NumLk, confirm that numpad 7 is now performing the Home function, switch back to the SharpKeys window, and press numpad 7 again in the TypeKey box, it still gives me "Num: 7 (00_47)". So while the NumLk state of the numpad seems to affect Type Key results on your numpad, it does not seem to on my numpad.

I don't know if this information will be of any help to Randy and his SharpKey experts in answering your question, but I'm throwing it in in case it could be of any use.

**Comment by SciencePiggy** [comment]
My best guess is that my issue is related to whatever is handling the media keys, which so far I haven't figured out how to disable. I've found that the Ease of Access Mouse Keys (using the numeric keypad to move the mouse cursor) also shows the same behaviour. Works as expected with NumLock on but does nothing when it's turned off (I did toggle the NumLock specific configuration)

I plan on pinging Lenovo directly on this issue.

**Comment by SciencePiggy** [comment]
Wasted 2 hours to be told they may be able to answer my question if I pay to upgrade my warranty. Maybe. Somehow I doubt that.

**Comment by randyrants** [comment]
Fn keys and their expected behavior are often hit and miss.  Media keys fall into the same bucket because there are a ton of instances where the key presses are trapped by the hardware or keyboard driver and don't get passed on to Windows through the regular keyboard handler.  This is why there are often 00_100 or no key strokes registered.  As an example, I run my Surface with Fn on all the time but flipped to be the inverted key.  So with Fn on, my top row is F1-F7 PrtSc Home End etc and with Fn off it's brightness -/+ Play/Pause speaker mute/-/+ keyboard light F8-12.  And at the same time, Fn is unremappable.

Depending on who the keyboard/laptop is from, there might be a driver they provide to give you control over the keys.

**Comment by SciencePiggy** [comment]
Thanks for the reply. I had no luck dealing with Lenovo support so I went with an AHK solution that "cannibalizes" my numpad while active. Not great but better than losing my common shortcuts.
