### ISSUE TITLE
Shift+Tab is Missing

### ISSUE THREAD

**Issue by bmdyer** [randyrants/sharpkeys#218]
I'm trying to map Tab and Shift+Tab.  Tab mapping exists, however, Shift+Tab does not
Thanks

**Comment by randyrants** [comment]
This tool cannot help as it can only remap entire keys.

From the FAQ, https://github.com/randyrants/sharpkeys#additional-faq-and-answers
Q: Can I remap a combination of keys to one key?
A: Sadly, no. SharpKeys only remaps whole keys rather than a modified key. For example, you can remap Ctrl or C but you can't remap Ctrl+C to another key.
