### ISSUE TITLE
It's possible adding ome keys?

### ISSUE THREAD

**Issue by luispinto85** [randyrants/sharpkeys#220]
Hello, i'm trying adding some keys at my keyboard in my but when i try to save say that key doesn't exist. Can you help me with that.
My keyboarb doesn't have keys to < and >, and i'm trying adding with AltGr+Z (<) and AltGr+X (>).

Thank you so much.

**Comment by randyrants** [comment]
This tool cannot help as it can only remap entire keys.

From the FAQ, https://github.com/randyrants/sharpkeys#additional-faq-and-answers
Q: Can I remap a combination of keys to one key?
A: Sadly, no. SharpKeys only remaps whole keys rather than a modified key. For example, you can remap Ctrl or C but you can't remap Ctrl+C to another key.
