### ISSUE TITLE
Console based usage

### ISSUE THREAD

**Issue by stdmatt** [randyrants/sharpkeys#223]
Hey @randyrants, congrats for the work!
I really appreciate the program and man, this is really, really useful to make my keyboard usable ;D

Well, I came from a unix background (OSX and GNU/Linux) and I really feel that SharpKeys could 
be more awesome if it's able to reassign the keys from a config file in the terminal. 

This will allow users to keep the configuration file (let's say in git) and apply the changes quite easily.

One flow that might be interesting would be like:

1 - Install sharpkeys from chocolatey. 
2 - Use the configuration file to apply the remap from terminal.

Something like:
```
choco install sharpkeys
sharpkeys --config-file path/to/the/file
```

I personally use chocolatey quite a lot setup my machines with the programs that I need to use,
and while I don't have the data I think that there's a lot of people that do the same looking by the 
size of the chocolatey  community.

To be very clear, this would be an addition to the program, all the GUI related functionality would 
continue the same, so existing users will have no troubles to use sharpkeys in the way the it is today.

I'd be very happy to add this feature if you feel interested and I'd like very much to hear your feedback on this as well, maybe you have something related planned or so. 

So let's talk and again congratulations and thanks for this piece of software!

See you ;D

**Comment by randyrants** [comment]
To be honest, there's no reason why this couldn't work with the Registry on it's own already.

If you have a set of remapping keys that you want to bring from machine to machine, you can simply open a CMD windows as an Admin and call reg add to set the remapping that you want (and then reboot).

This app only exists because I got tired of having to remember or lookup what the scancode was for a given key as my needs changed.  For more, take a look at the blog post that started the whole thing: https://www.randyrants.com/2002/05/down_with_caps/  That should help get you the information needed to create a .REG file or create a CMD file with a call out to reg.exe.

**Comment by stdmatt** [comment]
Hey man, thanks for the reply! 

I'll read the post! 

Continue the good job!

<3
