### ISSUE TITLE
trouble remapping keys (Mac --> W10 (via. bootcamp))

### ISSUE THREAD

**Issue by airpods1** [randyrants/sharpkeys#234]
I'm currently operating Windows 10 on my Macbook air through bootcamp because Excel has far better functions. Since my Macbook air keyboard doesn't contain the PgUp and PgDn key I can't switch between tabs on my worksheets. I tried to use sharpkeys to remap F7 -> PgUp and F9 to PgDn but it seems to ignore it completely. I don't know if this issue is because I'm using W10 through bootcamp 
![sharpkeys](https://user-images.githubusercontent.com/58206900/71788115-9527b080-3073-11ea-9740-084cb3be31de.PNG)

**Comment by airpods1** [comment]
Yeah so it looks like a new key that isn't recognised. This is for both F7 and F9

![F7 doesn't exist](https://user-images.githubusercontent.com/58206900/71788644-46304a00-3078-11ea-8bfa-c445e9a6e252.PNG)
![keying in F7](https://user-images.githubusercontent.com/58206900/71788645-46c8e080-3078-11ea-9381-2be3838f91df.PNG)

**Comment by airpods1** [comment]
I ended up remapping F3 and F4 to Pg Up and Pg Dn and it works! Thank you so much! It's a little awkward to press ctrl + F3/4 but now I can excel at excel!

**Comment by randyrants** [comment]
From a Mac hardware perspective, could it be that you were sending a function command rather than F7 and F9?  If I recall Bootcamp, it has an option to send the F-key value rather than the feature key (like Vol up/down) - I'm wondering if that's set (or not set) and using the Fn key at the same time is sending the wrong scancode.

00_100 is definitely tell you that a "generic unmappable" key was pressed.
