### ISSUE TITLE
Any chance you could compile for ARM for Surface Pro X?

### ISSUE THREAD

**Issue by Morid1n** [randyrants/sharpkeys#249]
I have a review unit of the Surface Pro X and would love to give SharpKeys a try. Only a few more days though...

**Comment by randyrants** [comment]
I wouldn't think you'd need it, since Surface Pro X should be supporting x86 apps under emulation OK?  Also, since this is using the .NET Framework, I explicitly compiled the most recent bits as "Any CPU" which means that it should run OK.  The MSI may not, but if you get the ZIP file version, that should run.

**Comment by Morid1n** [comment]
Thanks! Ran it today from the ZIP file and it worked like a charm.

I do have one suggestion, which I previously thought the app did: add the option to add new keyboard shortcuts e.g. Alt + Minus Sign = en-dash. Not sure if that's possible under Windows 10 or if it's in the scope of your app, but I'm really missing the ability to add a few custom shortcuts to make life easier.

**Comment by randyrants** [comment]
Sadly combo keys are outside of the scope of what the Windows remapping functionality can handle. I'd usually recommend AutoHotKeys but no idea if it works on x86 on ARM.
