### ISSUE TITLE
00_1D <-> E0_5B not working over RDP

### ISSUE THREAD

**Issue by ggrg** [randyrants/sharpkeys#253]
Hello. Thanks for the nice tool!

Seems it's not working properly for me, or I'm missing something? I've seen the similar issue posted over 2 yrs ago, but it didn't help. I'm accessing a remote machine that runs Windows 10 Pro using Microsoft Remote Desktop app for Mac. My mappings look like:
00_1d -> e0_5b
e0_5b -> 00_1d
e0_1d -> e0_5c
e0_5c -> e0_1d
I wrote to registry and rebooted without success.
Then I pressed Write to Registry over each entry and rebooted again - no difference.
I can not access the machine with local keyboard to confirm is it working or not, but it's certainly not with remote connection. I don't see why it would make difference if I used Type Key functionality and Sharp Keys recognises the above keys. Any recommendation would be greatly appreciated.

**Comment by randyrants** [comment]
Windows will be remapping whatever keys it knows about for the local keyboard.  Because you're coming from Mac, Windows doesn't have any local keyboard presses to change, which means that it is unable to remap them.

You would have to remap the keys on your local Mac keyboard in OSX if you want the changes reflected in Remote Desktop.  For example, if I've disable Caps Lock in OSX, you'll find it disabled in Windows as well.  If I disable Caps Lock in Windows, but OSX can still toggle it, Windows will also see Caps Lock pressed.

Just the nature of the remapping tool.  If you want to only do this in the remote session, you'd have to have an active remapper that sees "virtual" keyboard entries, maybe something like AutoHotKeys.
