### ISSUE TITLE
Sharpkey doesnt work with networked peripherals

### ISSUE THREAD

**Issue by brendandower90** [randyrants/sharpkeys#258]
I am currently using Sharemouse to share a keyboard over a local network to a second computer.
Unfortunately, this seems to have precedence over the keyboard buttons rather than the re-mapped keys on sharpkeys.

Is it possible to fix this so that sharpkeys is compatible with Sharemouse? Or any other networked peripheral application?

**Comment by randyrants** [comment]
Windows is remapping what it knows about, which means that it's always going to be the local keyboard.  Meaning that if you've disabled Caps Lock locally, and you are sharing your keyboard with another machine over a network, it's got no way to send the key over to the other machine because the key has been disabled.  As a huge fan of Mouse without Borders and Synergy before it, I've seen this scenario play out for years.

While it might be unexpected, Windows is doing what it's supposed to be doing, and there's no way to change that behavior.
