### ISSUE TITLE
can not remap F-keys to power-keys

### ISSUE THREAD

**Issue by thengineer** [randyrants/sharpkeys#26]
I am trying to map some function keys on my Apple keyboard (F16, F17, F18) to power, sleep, wake respectively as shown in the screenshot below. For reference, I mapped F19 to open Explorer.

![screenshot](http://i.imgur.com/tVzKAWc.png)

After rebooting, only the F19  does what it should (opens file explorer), the other power-related keys do not shutdown my computer in any way.

Is this a known issue?

**Comment by randyrants** [comment]
The three power keys - Wake, Sleep, and Power - are often different from machine to machine.  They're in the list because people have tried to remap from these keys to something else but it's always up to the hardware to send and/or interpret the keystroke.  It's likely that Windows is sending the command but the hardware isn't respecting it.
