### ISSUE TITLE
there are problem with binding left windows key to alt-language key

### ISSUE THREAD

**Issue by Xylphi** [randyrants/sharpkeys#263]
I am using 'keychron k6' which is newly released keybaord from kickstarter.

As I am using second language, I opened the sharpkeys and pressed [right windows key] (code : E0_5C) and bind it to [Hangeul key] (language switch key to korean, code : E0_F2)

I rebooted as the box instructs. Although I rebooted several times the binding doesn't work. It doesn't work either E0_5C or E0_F2 so I typed in the key which was originally right windows in sharpkey and I got [Unknown : 0xE072] (code is E0_72)

What  can be the cause?

**Comment by randyrants** [comment]
I know that the Windows key can be remapped - what I don't know is how well SharpKeys work for keyboards in other languages.  I've used a Japanese keyboard from time to time and I know that some stuff remaps while in en-US but all bets are off when it's in Hiragana or Katakana because the key codes change unexpectedly.  

Sorry it cannot be of more help!
