### ISSUE TITLE
Surface Book media key?  00_100 not recognized.

### ISSUE THREAD

**Issue by gatzke** [randyrants/sharpkeys#27]
Surface book does something screwy with function keys.  

By default, F5 is volume down.

To get F5, you have to hit the function lock key then hit F5/volume down.

Using SharpKeys I tried to map volume down (picking from list) to F5 so the keyboard F5/volume down always sends F5.  This did not work.

Using the typekey option, SharpKey reports key 00_100 is unknown and to check for an update.  

BTW, thanks overall.  I did get some other issues working with Sharpkey.  Awesome!

**Comment by gatzke** [comment]
BTW, found Microsoft Mouse and Keyboard center software that purportedly will allow key mapping.  Installed it and it apparently can't find a mouse or keyboard on my Microsoft Surface Book.  Nice!

**Comment by randyrants** [comment]
Volume keys are often intercepted in the hardware and do not pass their information to Windows itself, which means that there's no chance for Windows to remap the input.  Because this is on a Fn combo, it's almost likely not going to work.

As to the Microsoft Mouse and Keyboard center software, that is designed to work with USB-driven mice or keyboards from Microsoft - not the built in hardware of a laptop (even if it is a Surface).

**Comment by andyjia** [comment]
I'm encountering the similar problem. by default, on my bluetooth keyboard , when I push F2, It adjust the brightness as a media key, so I have push Fn+F2 to accomplish the normal function. 
I don't know why: Fn has appeared for many many years, why Fn has not be unified yet.

- the layouts are different.

Fn Control Option Command...
Control Fn Win Alt...
Control Win Alt...

- the actions are also different.

Fn +F1...F12 media key...
Fn +F1...F2 function key...

Is there any keyboard which is 
1.  Macbook layout for using on both PC and Macbook with similar experience.
2. Push F1..F12 to accomplish normal functions instead of pushing Fn combination.

**Comment by randyrants** [comment]
Fn keys are very often hardware keys: Windows does not know about the key because the key is not passed to Windows.

https://github.com/randyrants/sharpkeys#additional-faq-and-answers for more.
