### ISSUE TITLE
Windows / Arm builds

### ISSUE THREAD

**Issue by taxilian** [randyrants/sharpkeys#277]
Users of the surface pro x and possibly other devices with ARM processors would benefit from a version built for ARM =] I was able to build it in vs2019 on my surface pro x and it ran and worked perfectly.

**Comment by randyrants** [comment]
Actually the app is compiled as "Any CPU" and runs fine on an ARM PC.  I know this because an Pro X is sitting right in front of me.  The problem is the MSI: it is hardwired for amd64/x86 and installation programs are such a pain the ass, that I never, ever mess with a working script when I have one.  I once tried to convert it MSI to a WIX project and after spending two hours getting a VM up and running, I decided it wasn't worth the energy.

The ZIP version of the released 3.9 works fine.

**Comment by taxilian** [comment]
Ahh, good to know. MSIs are indeed a pain in the neck. I didn't think to try the zip.

**Comment by randyrants** [comment]
Indeed, I just added a callout for ARM users to use the ZIP instead of the MSI on the release page, so thanks for calling it out to my attention!
