### ISSUE TITLE
Feature request: Save/Load key combinations

### ISSUE THREAD

**Issue by science** [randyrants/sharpkeys#28]
I love your tool. I have a feature request - when my laptop is undocked and I'm using the built-in keyboard, I prefer one set of mappings, and when docked on a "real" keyboard I prefer an unmodified keyboard.

My feature request could be one of a few things:

1. Provide the ability to save and load keymappings to files, so different configurations can be used.
1. Provide ability to "disable" sharpkeys so that stored mappings are not in effect, until Sharpkeys is re-enabled.

I'd prefer option 1, but if option 2 were easier to implement, that would also solve my need! Thanks for considering this, and write back if you want any clarification on the idea.

**Comment by randyrants** [comment]
Option 1 has been asked about for a while but I've stayed away from it because it's already supported in the Registry.  For example, since I always disable Caps Lock on every machine, I keep a .REG file around and just run that when building/getting to a new machine.  That said, even after that gets installed, you still have to reboot.

The required reboot is why Option 2 doesn't appear to be viable.
