### ISSUE TITLE
Power Key

### ISSUE THREAD

**Issue by anick08** [randyrants/sharpkeys#283]
I have a key on my keyboard the shuts the computer down immediately when pressed. 
I want to disable it, problem is. IDK what key to say it is to make to "Turn Off Key" 
When I use the function that would allow you to type the key you want to map, computer shuts off. 
Help?

**Comment by randyrants** [comment]
If it immediately turns off screen and stops, it's likely Sleep and not Power Off.  If you go into your Power settings, there should be a "What should the Sleep button do" if you want to change it's behavior.

SharpKeys is not likely to be able to help with this as Windows will already be shutting down due to the hardware command that is forcing the Sleep/Shutdown.

**Comment by anick08** [comment]
Well, I know the difference between a sleeping computer, that can be woken up by a keyboard press, or mouse jiggle, and a total power off, boots from scratch situation. And it’s definitely shutting down. The screen the flashes momentarily is the Windows is shitting down splash page. 
And maybe your software can’t help, (although I’m curious what the key that is listed natively in sharp keys that you have labeled “Turn Off PC” is if not a power button) 
 But YOU did, because I can set what the power buttons behavior is too, same as your suggestion about the sleep button. 
THANKS

**Comment by randyrants** [comment]
Wasn't trying to say you didn't know the difference - I was basing this off of "shuts the computer down immediately" as "the screen goes black immediately" which doesn't happen for shutdown.  As you call out, shutdown has some UX that pops up.

And yep: I would have sent you to the same screen to investigate the "shut down" button behavior :)
