### ISSUE TITLE
IT Department

### ISSUE THREAD

**Issue by RAMATRON** [randyrants/sharpkeys#284]
Quick question - are there **any** instances of this program causing significant / unfixable issues to an operating system? I have used this on multiple machines and it has always worked great (nice job btw), but since changing jobs, my new IT department denied my request to install by saying:

_...this application was adjudged to represent a moderate risk because FAQ suggests that potential damage could be done to the Operating System when modifying the registry_

I replied with a link to the actual code saying that it is pretty straightforward and included "The fact that SharpKeys makes tweaks to the system registry could be considered a safety issue for some users. But that’s the only way for remapping keys, which means that all similar software tools do this. Nevertheless, it’s 100% safe, in the sense that it doesn’t damage your system. And, if you encounter any errors, you can easily fix your corrupt registry on Windows 10."

Am I crazy or are they? And if there haven't been any issues with this in current versions, could I ask that the FAQ they cited be removed?

**Comment by randyrants** [comment]
Sorry, but I'm not about to change the transparency of the FAQ of a free, open source product because there's an over zealous IT department being skittish.

Bottom line is that _any_ change to the Registry carries an implicit risk, including whatever the IT department runs on your boxes to set things up.  They use the Registry (as well as Group Policy Manager) to restrict features and settings which carries the same risk that SharpKeys would.  They are being a typical IT department, trying to protect their users by forbidding anything they don't know.

Say this runs on a new version of Windows - be it an update to 10 or a new architecture like ARM64 - and the scancode map moves or changes how it's stored?  It's not like Windows is going to email everyone about the change.  Now you boot to this new versions, but the old reg values are in there, which disables the whole keyboard.  I'm not willing to take responsibility for that.

Then there's also the ability to remap an entire keyboard to one letter or people that remap a key without realizing that they cannot type in their password now.  "I'm going to remap the E key to Q! Ha ha ha!  Wait, I'm trying to sign in but can't! [because my password is Hello!]"  You might think "No way!" but I get an email at least once a year for exactly this issue.

If you want to workaround this, you can make whatever changes you want to a computer that's not under their control, go into the Registry, find the Scancode map, export a .REG file - then bring that to your work computer, import the setting there (if it's allowed,) and reboot.  You don't need SharpKeys to use the Registry key that Windows uses to remap the keys - it's just easier to do it this way than hand configuring hex values in regedit.

Tell your IT folks that the source is online for them to review, the Scancode map hasn't changed since Windows NT 4.0 (maybe even 3.51) so there is only slight risk of problems there, no one can stop users from doing silly things with their PC's, and they can post here or email or Facebook if they are interested in getting more information.

**Comment by RAMATRON** [comment]
Thanks for the really thorough response. I understand your points - essentially there is no foolproof way to do anything (especially if the operator is a fool ;). IT has locked down any changes to the registry whatsoever yet somehow asked "If you have another software you can find, please submit via the Software Installation Request page".  Hmmmm.... ok?

I also get your point about transparency, but I don't think they have any actual interest in understanding what the program does, nor do they want to facilitate a solution. Bummer.

Thanks again for responding.

**Comment by randyrants** [comment]
Another option is PowerToys, from https://github.com/microsoft/PowerToys/releases - they remap keys using an active remapper, rather than relying on the Windows remapper (which is why the Registry is involved.)

HTH!
