### ISSUE TITLE
Multimonitor / Settings restoration bug

### ISSUE THREAD

**Issue by grasmanek94** [randyrants/sharpkeys#293]
Hey there, the following code during startup:

               nWinState = (int)regKey.GetValue("MainWinState", 0);
                rc.X = (int)regKey.GetValue("MainX", 10);
                rc.Y = (int)regKey.GetValue("MainY", 10);
                rc.Width = (int)regKey.GetValue("MainCX", 750);
                rc.Height = (int)regKey.GetValue("MainCY", 550);

                nWarning = (int)regKey.GetValue("ShowWarning", 0);

Makes it impossible for Sharp Keys to show itself when my monitor settings/layout changes (connecting/disconnecting monitor).

Maybe also save more variables? Or just don't restore window size?

**Comment by randyrants** [comment]
Well the good news is the source is out there.  I'm not going to remove the restore window position because I like it.  Also, as it's defaulting to open at position 10, 10, it should be visible on any 1024x768 screen.  Is it that you're moving it to somewhere far from the corner and then you are changing back to another screen that has less resolution?  I think that if it you open it and have no reason to move it, it will always open at a visible location.

Or is there something else here I'm not grok'ing?
