### ISSUE TITLE
SUGGESTION: Record Unknown keys Option (it asks for what they are) Send in Email?

### ISSUE THREAD

**Issue by dbareis** [randyrants/sharpkeys#303]
Quite a few keys on my keyboard are not able to be mapped. 

IFF it's vital that they are added to the app then I'd like an easy way to record and report them built into the app.  Otherwise, why can't I use it anyway if I want to remap it (you have recorded the key codes)?

**Comment by randyrants** [comment]
No way in hell. :)  I mean, I don't want to have a collection of keys from a dozen different versions bombarding my inbox.

In fact, the whole reason I put the source onto GitHub was so other developers could get involved in the project.  For example, someone created this pull request https://github.com/randyrants/sharpkeys/pull/296 to correctly label two scan codes that are unique to a Japanese keyboard.  That's how I've hoped this program would evolve.

**Comment by dbareis** [comment]
Well email was one option copy/paste into a github issue is another.  No way am I going to copy them down by hand.  So your app will remain without the extra key details.  I also suggested that why can't we remap them ourselves, seems like you say you don't want to be involved yet you close the issue.  Plenty of other similar apps around, see ya.

**Comment by randyrants** [comment]
To be clear, I saw "let people send you an email when there is an unknown key".  I answered that with a No and why.  I also took the time to point out how people can get involved in helping other people, by posting new keys.  You then go on to tell me that I don't want to be involved?  Hey, I keep a tidy board - my repo, my project, my option - and I've no interest in leaving the request open.  Your post is #303 with the other 302 that are either requests that have been answered or my answers to people as well as taking a bunch of pull requests.   Doesn't mean I've taken every PR or acted on every feature request but if my free app doesn't do what people want (like remap Shift + 2 to something or support triple-byte codes) I suggest they try AutoHotKeys or Microsoft's PowerToys.   

And with all of that said, Unknown scancodes - such as Unknown: 0x007A - are fully supported and can be used.  If you are getting scancodes like 00_100 or just a flat out "we don't see this key" or "don't know what to do with it" then there is no amount of coding that is going to help get those into the product.  All of this is called out in the FAQ as well, but the very simple fact is that if Windows cannot see the key, SharpKeys cannot tell Windows to remap it because Windows is doing the remapping.

If after all of that, you think that I'm showing a lack of interest or support for my project, don't let the virtual door tap ya on the butt on the way out and have a nice day.
