### ISSUE TITLE
Feature Request: allow custom keycodes usage

### ISSUE THREAD

**Issue by markstinson** [randyrants/sharpkeys#31]
I've a Windows 2-n-1 laptop & keyboard dock. Lacking an ESC key (besides Function keys), I went to learn what Fn+Search (magnifying glass) [ 00_100 ] and received the error (like those with foreign layouts): "You've entered a key that SharpKeys doesn't know about"

Would it be possibly for include the feature allowing folks to enter the key hex codes for such situations?
Thank you for reviewing this request. Cheers.

**Comment by Kharmium** [comment]
I second this petition. Right now I bought a new mechanical keyboard and although I love it, it lacks  Fn Lock. 

I was hoping I could reverse the custom keys (Fn+Key) to the actual F keys and vise versa, but I'm also getting the "You've entered a key that SharpKeys doesn't know about" message. :(

**Comment by randyrants** [comment]
Likely not going to be supported because Windows doesn't know what to do with it.  Fn in particular introduces all sorts of commands that could get intercepted by a hardware driver, such that Windows never gets it.  00_100 is what Windows gets which can be literally any key Windows doesn't know about.

If you wanted to muck around with the hex values directly, you can do so via the Registry but a) I'm not encouraging this and b) I'm not responsible if you end up remapping unexpected keys that prevents you from signing in.  #caveat_emptor
