### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by NathanDai5287** [randyrants/sharpkeys#320]
It would be really helpful to have a folder that is just an archive of common keyboard layouts. I did some googling and couldn't find any, so I manually made a Colemak layout skl file. [link to post](https://www.reddit.com/r/Colemak/comments/jad8zy/can_anyone_help_provide_a_colemak_configuration/)

**Comment by NathanDai5287** [comment]
This is also my second time "contributing" so please don't destroy me

**Comment by randyrants** [comment]
I think you're the second person I know of that has used the "save layout" feature :) 

I mean I know I exported my layout for what I do for Surface but I didn't think anyone noticed!

**Comment by randyrants** [comment]
Updated the readme with a pointer to the SKL file on Google Drive - thanks!

**Comment by NathanDai5287** [comment]
Could you change this link to this GitHub repo rather than the Google Drive? I'd prefer to not expose my email like that. Thanks :)
https://github.com/NathanDai5287/Keyboard-Layouts-for-SharpKeys

**Comment by randyrants** [comment]
Sure

**Comment by otraver** [comment]
Hi, I attached the saved layout for the BMAX Y13.
Is incomplete because I can't remap the action key F2 (Keyboard backlight), F6 – Screen Brightness down, F7 – Screen Brightness up, F8 – Fly mode and F12– second display config
[BMAX Y13.zip](https://github.com/randyrants/sharpkeys/files/5672783/BMAX.Y13.zip)
