### ISSUE TITLE
Can't remap <> key (this is NOT ,< or .>!)

### ISSUE THREAD

**Issue by Martamima** [randyrants/sharpkeys#33]
I am trying to map the key on my keyboard that types < and > to Special:Left Windows (E0_5B.  But when I try to add it to the left column, I get either ,< or .> - but NOT <>

Example:
![sharpkeys glitch](https://user-images.githubusercontent.com/30706321/28946631-9e4398c8-7879-11e7-9c80-4a9706faeb42.PNG)

I understand that the first remapping shown above is not what I want (the second works fine) - in fact messes me up.  But I can't find Key:<> in the left column. Can someone help? Is it one of the "Unknown:" keys? Do I need to figure out about Dip switches on my (OmniKey/Ultra) keyboard first? The key reliably types < and > - I used it to type this. Thanks in advance.

(The second remapping, of the stand-alone * key, works just fine.)

**Comment by randyrants** [comment]
There are several things with the above, first and foremost is that there is no < or > key on any keyboard I've seen.  The whole key gets remapped with this technology: to get < you are actually typing Shift+,

The above setting will remap the , key to Left Windows successfully.  When you try using Shift+, you are trying to type Shift+Windows which I believe does nothing.  At least it doesn't do anything on my keyboard, when I use the actual key.  

There is no way to remap "half" a key or a modified key with this tech: the whole key gets remapped and then any modifiers get applied to that.  If your physical keyboard has a dedicated key for < and > I have no idea what the scancodes would be, because such keys don't typically exist in the 103-key keyboard, much like how I have a =, (, and ) key on one of my keyboards - Windows doesn't know what to do with it.

HTH!

**Comment by Martamima** [comment]
I'm sorry you can't do something about this.  It really IS a real key, not even a custom one, but I guess not all that common.Best, MarthaOn Sep 26, 2017 5:30 PM, Randy <notifications@github.com> wrote:Closed #33.
