### ISSUE TITLE
Add ability to re-map unknown buttons

### ISSUE THREAD

**Issue by Alex-302** [randyrants/sharpkeys#349]
For example, Jelly Comb [K62B-3](https://www.jellycomb.com/products/k62b-3-bluetooth-keyboard) has Home button, which I want do disable, but SharpKeys does not know about it.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/108699661-31c63f80-750e-11eb-9450-7a18b25c4dbc.png)

![image](https://user-images.githubusercontent.com/8361299/109479059-ae16d080-7a82-11eb-8743-142c62f7a204.png)

</details>

**Comment by sdsnatcher** [comment]
I have the same problem with the Apple Remote. Its buttons also show up as (00_100).

Curiously enough, [this online keyboard checker](https://keyboardchecker.com) detects its PLAY/PREVIOUS/NEXT buttons just fine on Firefox on Win10.

The Volume up, Volume Down and MENU buttons are not detected neither by SharpKeys or the online keyboard checker though.

**Comment by KGBurton** [comment]
I can't remap the calculator button on the MS ergonomic keyboard (code 00-100) because it is unknown.

![2021-02-28 , 10_47_18 Screenshot -](https://user-images.githubusercontent.com/77697345/109428029-57da5c80-79b2-11eb-9115-c69aaaa79a8b.png)
![2021-02-28 , 10_45_17 Screenshot -](https://user-images.githubusercontent.com/77697345/109428018-46915000-79b2-11eb-9ad3-f7366366b847.png)

**Comment by randyrants** [comment]
This is all covered in the FAQ: 00_100 is not a valid code and is typically a hardware key that cannot be remapped.  Please give Microsoft's PowerToys a try.

**Comment by Alex-302** [comment]
> Please give Microsoft's PowerToys a try.

It works in my case. Thanks.

**Comment by sdsnatcher** [comment]
PowerToys doesn't have a 32bit version, so I still have no solution.
