### ISSUE TITLE
Scoop couldn't find manifest for sharpkeys

### ISSUE THREAD

**Issue by aannaazh** [randyrants/sharpkeys#351]
I've added the extras bucket in `scoop`, and is able to successfully install other packages

but the command `scoop install sharpkeys` doesn't work, it returns 

`Couldn't find manifest for 'sharpkeys'.`

**Comment by randyrants** [comment]
I'll leave this open but I had nothing to do with getting this hosted on scoop so I have no idea.  I added it to WinGet (because that's what I use) but given all of the package managers out there (WinGet, Scoop, Chocolate, Nuget, etc.) I'm leaving it up to the people that use the other services to get that up and running.

**Comment by jaden-young** [comment]
FWIW I was able to install version 3.9.2 today with `scoop`.

**Comment by randyrants** [comment]
Nice!  Thanks for the update!
