### ISSUE TITLE
Remote-Keyboard - Minix Neo A2 Lite - Play-Pause

### ISSUE THREAD

**Issue by minix-remote** [randyrants/sharpkeys#360]
Dear Randy,

Thank you for creating this simple and very useful software.

I tried to remap the "Play-Pause" front key of the Minix Neo A2 Lite Remote-Keyboard to be a second "Space" key, but it didn't work.

When I click on the button "Add" and then "Type Key" it shows "00_100". Then I press "OK". But after that, a message tells me "You've entered a key that SharpKeys doesn't know about. Please check the SharpKeys website for an updated release".

Additional informations: The Minix Neo A2 Lite works out of the box with Windows 8 (including the front "Play-Pause" button, the front "Up/Down/Right/Left" buttons, the front "Volume-Up/Volume-Down" buttons, the front mouse-pointer and the back QWERTY full keyboard) for all apps installed on the PC (VLC, Windows Media Player, LibreOffice, etc), except for certain streaming websites on the browser (Firefox). That's why I would like to remap the "Play-Pause" button to be a second "Space" button.

Do you think you could fix that problem ? That would be really cool.

Best regards

Minix-remote

**Comment by randyrants** [comment]
From the FAQ:
Q: Type a Key shows 00_100 - can I remap this key?
A: 00_100 is a catch all code that Windows reports when a key is captured by hardware or some other driver so there's no way to successfully remap that key, especially since multiple keys can return the same 00_100 code.

Please try Microsoft PowerToys or AutoHotKeys.
