### ISSUE TITLE
Factor out the key names to a JSON file?

### ISSUE THREAD

**Issue by mk-pmb** [randyrants/sharpkeys#361]
Hi! Thanks for maintaining a list of keycodes and useful names for them. I'd like to use that for a website (SPA) that generates appropriate REGEDIT4 files.

What do you think about splitting out that list of keycode -> name to a JSON file? I could generate that for you if you like. That way it would be easier to reuse in software written in other languages.

Would you be willing, and have appropriate permissions, to maybe share that resulting dictionary under a more compatible license, like LGPL or MIT?

**Comment by mk-pmb** [comment]
Actually, it was so easy to convert I just went ahead and created [a draft](https://github.com/mk-pmb/sharpkeys/blob/draft-keynames-json/SharpKeys/keynames.json), and also configured that branch for GitHub Pages so it's [available as raw JSON](https://mk-pmb.github.io/sharpkeys/SharpKeys/keynames.json).

Of course it would still be nice to have it in your repo for better discoverability and centralized maintenance. Also if you as original maintainer repeat my conversion effort (possibly producing the same bytes), you may be entitled to grant better licenses on your resulting file.

**Comment by randyrants** [comment]
Given that the list of keys gets changed around once every 18 months, I'm not inclined to take on the work required to make a dynamic list that gets loaded/unloaded.  I mean of all the new keys appearing on new keyboards, all of them have been either triple-byte (not supported) or hardware based (show up as 00_100) so there's not much growth there either.

Especially since it quintuples the attack surface for issues, since files can now be loaded dynamically. I also think there might be a closed pull request that already did this work; I fully support people forking the repo and changing the app to fit their needs.
