### ISSUE TITLE
Allow remapping of E1_1D (Pause key)/Implement list merging

### ISSUE THREAD

**Issue by GucciMembrane** [randyrants/sharpkeys#362]
From what I understand, even though the scancode for Pause is much longer, but changing the values for this key should allow for remapping the Pause key. I've seen a mod to the SharpKeys accomplish this with only one new line of code.

Also:
I've been able to get the registry-editor-made value to appear in sharpkeys, although it clears my other remaps. Merging remap lists would be very helpful in this case so I can add registry-defined remaps to my existing scheme.

And one more thing:
After trying to manually copy my list of remaps, I saved it, wrote it to the registry, and restarted my PC. I opened sharpkeys back up, and E1_1D became App: Calculator.

**Comment by randyrants** [comment]
I'm not likely going to add a partial key code for Pause because there's no guarantee that it will not interfere with other keys that start with E1_1D.  That said, you can fork the repo and do whatever you like with it: that's the whole point of github.

Likewise, if someone wants to invest in merging lists or different keys together, that can also be coded, I think.

For the remapping of Pause, I recommend using a more active re-mapper like Microsoft PowerToys: their tech is not built into Windows so they have a lot more flexibility to work with.
