### ISSUE TITLE
Sticky keys not able to work with some games?

### ISSUE THREAD

**Issue by realDonkeyDong** [randyrants/sharpkeys#369]
I'm reading here and there it's looking like this app won't help me 'universally'. Sucks that games don't take the input from windows. Why would they do that? Sadly I've found 'Call of the Wild: The hunter', 'Phasmophobia' seem to have this problem. 
Sorry to ask here, but is there another program or tool I can use to rebind keys for all input? I am desperate to find a solution where I can rebind the keys at a level everything accepts it... :(

**Comment by randyrants** [comment]
Indeed, for this app, if they keys don't get passed to Windows, Windows doesn't have a chance to remap it.  Microsoft PowerToys may do better, since that's an active remapper.

As for games, it depends on the game: KM is a hair faster if they take control over at the hardware level, rather than letting Windows pass it along to them.  Other games just read off XINPUT and then the remapping usually works.  Games usually code outside the norm of a "regular" Windows app.
