### ISSUE TITLE
Windows 10 Media Keys

### ISSUE THREAD

**Issue by dougclift** [randyrants/sharpkeys#373]
Looking to use Sharp Keys and it's not recognizing the following buttons on my keyboard
AudioVolumeUp
AudioVolumeDown
AudioVolumeMute

Then there is a button that opens a windows file explorer which I can't seem to identify. 

How could I get those keys recognized by Sharp Keys?

**Comment by drtassen** [comment]
you need to find dem inn the right list "manuel" ^^

**Comment by randyrants** [comment]
It depends on the keyboard: some are supported and some send in 00_100 because they talk to Windows through HW interrupts.  You will find the keys above in the Media section of the list of available keys if you want to give it a try.  If not that, try Windows PowerToys as they have a more active remapper bit in there.
