### ISSUE TITLE
Unrecognized key on HP Pavillion 600 keyboard

### ISSUE THREAD

**Issue by BlueChipDevelopment** [randyrants/sharpkeys#379]
SharpKeys does not recognize a specific key on my HP Pavillion 600 keyboard.
- https://www.hp.com/us-en/shop/pdp/hp-pavilion-wireless-keyboard-600

This keyboard has the annoying feature that you have to use the fn function to use the F1-F12 functions. Therefore, I would like to map the F5 on my keyboard to the fn-F5 feature. Unfortunately, SharpKeys does not recognize the play/pause button yet. 

It would be great if we could add support for this key somehow?

![Not an existing key](https://user-images.githubusercontent.com/39616343/123280879-789e6300-d509-11eb-9760-aa20421c7505.PNG)
![The Key](https://user-images.githubusercontent.com/39616343/123281755-3aee0a00-d50a-11eb-9419-80b36c5a6fa1.png)

**Comment by randyrants** [comment]
From the FAQ, https://github.com/randyrants/sharpkeys#additional-faq-and-answers:

**Q: Type a Key shows 00_100 - can I remap this key?**
A: 00_100 is a catch all code that Windows reports when a key is captured by hardware or some other driver so there's no way to successfully remap that key, especially since multiple keys can return the same 00_100 code.
