### ISSUE TITLE
How to add £ symbol

### ISSUE THREAD

**Issue by lasagneking** [randyrants/sharpkeys#383]
Great app, thanks for your work.

I'm in the UK although I have a US keyboard.

I have the dollar $ sign on key 4 and I simply want to replace that with the pound £ sign.

I can find the key to map from although under the (to key) section, I cannot find an option of adding the £ symbol although there appears to be entries for the euro and yen.

Is there anyway of achieving my aim?

Thanks in advance

**Comment by randyrants** [comment]
Per the FAQ, https://github.com/randyrants/sharpkeys#additional-faq-and-answers:

**Q: Can I remap a combination of keys to one key?**
A: Sadly, no. SharpKeys only remaps whole keys rather than a modified key. For example, you can remap Ctrl or C but you can't remap Ctrl+C to another key. That said, the Microsoft PowerToys tool does offer this functionality - you can learn more about their tool here: [Microsoft PowerToys](https://github.com/microsoft/PowerToys/releases).
