### ISSUE TITLE
Donation link

### ISSUE THREAD

**Issue by definelicht** [randyrants/sharpkeys#387]
Feature request for a donation method to be linked from `README.md`. I had to go through the blog to find it 🤑

**Comment by randyrants** [comment]
That is a very good suggestion :)  Thanks for the donation!

**Comment by ashishdha** [comment]
worked! got my '??' back after ages and ages, thanks to you (and ChatGPT who pointed me to you!)!

donated a dollar. thanks :)

**Comment by randyrants** [comment]
Thanks!

**Comment by ashishdha** [comment]
you've very welcome!

it's really helped :)

and btw, chatgpt recommended sharpkeys, which is why i got it :)

*Ashish Dha*

*Composer-Musician, Music Teacher, Sound Designer, Voice Artiste, Actor*US
mobile: +1901444875
WhatsApp & Indian Mobile: +919013899572
Irish mobile: +353899410686

Website: ashishdha.com
Skype ID: ashishdha
Soundcloud.com/ashishdha
Facebook.com/ashishdha
Youtube.com/ashishdha
Instagram.com/ashishdhanaadaalay
Twitter.com/DhaAshish
