### ISSUE TITLE
Remap media keys on Corsair K83 (Powertoys can do it)

### ISSUE THREAD

**Issue by inertia666** [randyrants/sharpkeys#391]
I am trying to remap my media keys on my Corsair K83 and I get the 100 code so cannot map them.

I can remap these keys easily with Powertoys but it is introducing other problems so I cannot use this remapper.

Why can Powertoys identify these keys but not Sharpkeys?

**Comment by randyrants** [comment]
Because PowerToys is built around using an active remapper - meaning they have a much better shot at getting hardware keys and triple-byte character scancodes - where as SharpKeys is simply storing data to a Registry key that Windows then uses to remap keys on it's own.

The  FAQ should include all of this, including a callout to get PowerToys if you need active remapping.
