### ISSUE TITLE
Remapping the Tab key

### ISSUE THREAD

**Issue by ChuloOnwuta** [randyrants/sharpkeys#393]
Hi, I just downloaded the app about 3 days ago in an attempt to remap my TAB key to another key after it stopped working.

I started off by mapping it to my 'A' key as a test, which worked well after restarting my computer

I then remapped it to my function keys that don't do their suggested action (ex function 2 does the CTRL+F command), but to no avail.
Thinking it was a problem with my function keys, I remapped to my right windows key but it STILL didn't work. I finally tried my right CTRL key but, again, nothing.

After every remap I rebooted my computer, opened up the app, and accepted permissions.

If someone had a similar problem or could help that would be much appreciated, thank you so much.

EDIT: I downloaded the 3.9 MSI version on the randyrants website

**Comment by randyrants** [comment]
You cannot remap combined keys, per the FAQ, [on the home page](https://github.com/randyrants/sharpkeys#additional-faq-and-answers) 
**Q: Can I remap a combination of keys to one key?**
A: Sadly, no. SharpKeys only remaps whole keys rather than a modified key. For example, you can remap Ctrl or C but you can't remap Ctrl+C to another key. That said, the Microsoft PowerToys tool does offer this functionality - you can learn more about their tool here: Microsoft PowerToys.
