### ISSUE TITLE
Special: Right Windows not registering

### ISSUE THREAD

**Issue by ktm4ck** [randyrants/sharpkeys#394]
When you hold the Windows Key and press Arrow:Right or Arrow:Left directional keys on the keyboard, they both show as "Special: Left Windows(E0_5B)". 
 
Also when you do remap either of these keys (I selected in dropdown even though the keypress method isn't working), behavior is strange. It doesn't seem to be working as expected.

**Comment by randyrants** [comment]
Behavior is as expected because you can only remap a whole key, rather than Win+LeftArrow.  If you want Right Windows key, this is the Windows key that's on the right of a given keyboard, if the keyboard has once.  For example, a Surface cover keyboard only has one Windows key but other desktop keyboards have two.

**Comment by narasihma** [comment]
"Special: Left Windows(E0_5B)" isn't even on my list of keys im able to remap. Which is quite unfortunate because it's what my 7 button vertical mouse has one of the keys assigned to.
