### ISSUE TITLE
Mapping AltGr does not work

### ISSUE THREAD

**Issue by srmagura** [randyrants/sharpkeys#402]
## Steps to Reproduce

1. Map AltGr to Right Alt in SharpKeys:
![sharp-keys-before](https://user-images.githubusercontent.com/801549/138611048-c52e31cd-8af2-4a05-be22-b6b3f854f412.png)

2. Click "Write to Registry".
3. Restart PC and open SharpKeys. The mapping now shows Right Alt instead of AltGr:
![sharp-keys-after](https://user-images.githubusercontent.com/801549/138611053-40154473-b24d-4a8b-9bbc-6924b718a247.png)

## Additional Context

I am using Colemak on Windows 11.

**Comment by oroboros** [comment]
I am unsuccessful in remapping Right Alt to AltGr as well.

**Comment by wds-qian** [comment]
Version 3.9.4 works very well for my setup with Alt+Gr.
I am using Sharpkeys on a Windows 11 VM under Parallels with an external German PC/Windows keyboard. I have my Mac setup to use the German PC keyboard layout, so it is consistent between Windows and Mac. 

My Sharpkeys config:
[parallels_pc_keyboard.skl.zip](https://github.com/randyrants/sharpkeys/files/8482309/parallels_pc_keyboard.skl.zip)
![image](https://user-images.githubusercontent.com/92719593/163203346-134b56fa-b685-41a2-8a27-d09e8680a3da.png)

My Parallels profile setup:
![image](https://user-images.githubusercontent.com/92719593/163203473-c5a7b3e6-afda-4c6b-bccf-219d3a018b00.png)

Keyboard modifier setup:
![image](https://user-images.githubusercontent.com/92719593/163203847-3fc4d0f6-5ada-4fd1-a3ad-ee8fca27ee76.png)
![image](https://user-images.githubusercontent.com/92719593/163203878-1b6fc6eb-d182-417f-8067-dce5c06af4a6.png)

Keyboard profile for mac:
https://github.com/skrysmanski/windows-pc-keyboard-layout-mac

**Comment by randyrants** [comment]
Going to close this down as AltGr has been removed from the list of keys in current builds.

**Comment by lucas-teks** [comment]
SharpKeys is very basic I think it modify the registry based on scancode so this recognized only key pressed/released individually. Maybe not the same with PowerToys keyboard manager because you can map to a combination, but sadly not use a combination as input.

**Solution:** for combinations (with AltGr, Fn, Ctrl etc) you should consider it as macros thus run a simple .ahk AutoHotKey script at windows startup, works perfectly! Some characters might require to be followed by an escape sequence (`) such as `!` or `:`

**Comment by DreymaR** [comment]
> I am unsuccessful in remapping Right Alt to AltGr as well.

That's really not how it works. The OS interprets the RAlt key as either RAlt or AltGr, depending on the active system layout. Techincally, the Windows definition of an AltGr key press is LCtrl+RAlt, but that's an unnecessary distinction in most cases.

So you should not remap RAlt to AltGr! If your OS layout uses AltGr, any RAlt key press will be interpreted as AltGr.

**Comment by DreymaR** [comment]
> Going to close this down as AltGr has been removed from the list of keys in current builds.

I agree fully with this decision.

Just make sure your documentation clearly states that the OS will handle RightAlt key interpretation as either pure RAlt or AltGr depending on the active keyboard layout. This is true both for Windows (where it's an integral part of the layout's DLL) and Linux/XKB (where it's an option that's activated for layouts using AltGr). Probably for MacOS too, but since I don't use that I can't vouch for how it's implemented.
