### ISSUE TITLE
Is it possible to use SharpKeys on Windows 11?

### ISSUE THREAD

**Issue by lauma** [randyrants/sharpkeys#411]
I tried installing SharpKeys on fresh Window 11 and got following error:
![image](https://user-images.githubusercontent.com/1726889/143913714-686b4e1f-4ce9-4e2d-adb8-04fbaec7a200.png)

I scrolled through the version list and noticed that a while ago support for .NET 4.0 is added, but don't know how to install that, because my windows protests like this:
![image](https://user-images.githubusercontent.com/1726889/143914054-43c5fa78-71fe-46ab-8671-34d1cc83ef81.png)

Thanks!

**Comment by randyrants** [comment]
SharpKeys works on Windows 11 without an issue however, you have two different error messages:  the first is asking for .NET 2.0 which likely means it's a super old build and the second is failing to install .NET 4 because it's already installed.

I would uninstall SharpKeys and get the most recent build from https://github.com/randyrants/sharpkeys/releases and start again.

**Comment by lauma** [comment]
Thanks, that helped. I was somehow convinced that I already was trying the newest version, bet I was wrong.
