### ISSUE TITLE
Any way to load profiles via command line or reassign keys through command line?

### ISSUE THREAD

**Issue by SyRaza** [randyrants/sharpkeys#415]
I'd like to try and automate the process as much as I can. I have to reassign some keys depending on the programs I'm using. As the title says, curious if there is a command line argument or a direct command to reassign keys that I throw into a batch file?

I was thinking of doing the regedit method but I don't know how to back up my default keymap.

Any help would be appreciated. Thanks

**Comment by randyrants** [comment]
Not really in scope for SharpKeys, since the whole point of having this app was to have a UX to interact with the Registry Key Windows uses to remap keys.

To that end, you can easily use reg to inject change the Scancode Map value whenever you want to, but you'll still need to reboot for the change to take effect.
