### ISSUE TITLE
Not working on games

### ISSUE THREAD

**Issue by nibco** [randyrants/sharpkeys#433]
When I try to use my remap on a game, it doesn't work. 
(Ex: If I remapped my W to R key if I pressed R I wouldn't go up)

**Comment by randyrants** [comment]
Hi - games are tricky because they often have their own keyboard stack handling the input.  Makes it easier/faster for game play, as it doesn't have to round trip through the Windows stack.  You can try something like PowerToys as that is a more active re-mapper or see what you can do from within the game itself.
