### ISSUE TITLE
Turning key off still sends 00_00 event

### ISSUE THREAD

**Issue by ns-studios** [randyrants/sharpkeys#434]
I'm not sure if there's anything that can be done about this, but since one of my keys has been going off constantly, I wanted to disable it, but it seems that when you set the key to turn off, it still sends the unknown 00_00 key event that some apps still catch.

**Comment by randyrants** [comment]
This is wild.  I mean, the only reason why I set it to 00_00 is because that's what Windows tells you to use for disabling a key.  Had no idea that 00_00 was a valid key code.

Sadly, you're right: there's nothing that I can do for this, as the remapping tech is all up to Windows.  You might want to try Microsoft PowerToys as they are a more active remapper and might sidestep this issue.
