### ISSUE TITLE
Unknown Key (00_100)

### ISSUE THREAD

**Issue by MysticLevi** [randyrants/sharpkeys#436]
One of my keys was set to the key in the title, your software didn't recognize it. Just thought I'd let you know... All I know is that it turns my volume up to 100.
![Capture](https://user-images.githubusercontent.com/101525787/158076721-27570196-2c44-4ec5-babe-0d61c3676227.PNG)
![Capture2](https://user-images.githubusercontent.com/101525787/158076725-f9e4b0ce-05a8-44db-8c98-c403c7588028.PNG)
@randyrants

**Comment by randyrants** [comment]
Per the FAQ: https://github.com/randyrants/sharpkeys#additional-faq-and-answers

**Q: Type a Key shows 00_100 - can I remap this key?**
A: 00_100 is a catch all code that Windows reports when a key is captured by hardware or some other driver so there's no way to successfully remap that key, especially since multiple keys can return the same 00_100 code.
