### ISSUE TITLE
BUG 3.9.3 Program window is cut off at the bottom

### ISSUE THREAD

**Issue by useforgh** [randyrants/sharpkeys#439]
Tested on Windows 10 21H2 the 3.9.0 + 3.9.3

I can expand the 3.9.3 window but it keeps the same style.
Not tested whether the msi has the same problem.

The 3.9.0 works without problems.

**This is what it looks like in practice**

![this window is cut off at the bottom - 3 9 3](https://user-images.githubusercontent.com/101951685/159138923-15efe291-d676-4efa-8d4c-ef843ef10e35.jpg)

I guess: the white area with the list of "Map this key:" + "To this key:" uses more space than the previous version. Maybe that's the main problem.

**Comment by randyrants** [comment]
Never seen this one before.  I know that I did a bunch of changes to theme support, where the past versions were not supporting high contrast as it should have been, and in doing that it might have shifted some of the sizing around, but I have no idea why it would be happening on some screens but not others.  Especially since I run on a ton of Surfaces which always run at something other than 100% DPI.

What's your resolution and DPI settings?

**Comment by randyrants** [comment]
Indeed, as I called out the 3.9.3 and 3.9.4 releases added better support for the high contrast themes which also means that the UX itself has more freedom to resize itself as it sees fit.  Given the age of the laptop (I think it released in 2005) and the smaller resolution, I would recommend sticking to 3.9.2.  There aren't any new noteworthy features in the last two releases - bug fixes mostly - so it should be stable.  And still available on the releases page:  https://github.com/randyrants/sharpkeys/releases
