### ISSUE TITLE
Bloomberg Keyboard 4 volume up/down/mute not recognised

### ISSUE THREAD

**Issue by Doggie52** [randyrants/sharpkeys#449]
The volume up, volume down and mute buttons on the [Bloomberg Keyboard 4](https://data.bloomberglp.com/professional/sites/20/bloomberg_keyboard_4_guide.pdf) are not recognized by the application. Any chance they can be made recognisable? Currently they map to the keyboard's internal audio driver, which is annoying as I'd rather they map to the computer's global audio driver (i.e. the regular volume up/down/mute buttons).

**Comment by randyrants** [comment]
Been a long, long time since I've gotten my hands on a Bloomberg terminal.  Always an adventure.

Sadly, media keys are very often trapped by HW and don't get sent on to Windows for remapping.  Given Bloomberg's long standing tradition of custom HW, I have no idea where the scancodes are going, but if they aren't getting to SharpKeys, they are not getting to Windows either.  Give PowerToys a shot, if IT will let it be installed.  It's got a more active approach to remapping keys.

**Comment by Doggie52** [comment]
Thanks for getting back to me so quickly.

I did give PowerToys a shot - it actually manages to read the input as "Volume Up", for example, but then I cannot remap that to some "global" version of "Volume Up" because it says "cannot remap key to itself"...
