### ISSUE TITLE
Context-Menu key on Surface Pro not remappable

### ISSUE THREAD

**Issue by sirtet** [randyrants/sharpkeys#456]
I selected the key by keypress, the result was 
Special: Application (E0_5D)
I mapped this to NUM: + (00_4E)
But after a logout, the Key still is context-menu (Tested in notepad.exe)

**Comment by sirtet** [comment]
My bad, i was doing the remap on a Server 2019, through RDP.
Now i installed and remapped locally, and the remap is forwarded through the RDP session as expected.

The fact that it did not work on the Server should/could maybe a separate Bug report?

**Comment by randyrants** [comment]
This is by design, actually.  SharpKeys only impacts the local physical keyboard.  I mean, that you installed it to Server via remote desktop, it will work fine there but only on the Server's locally plugged in keyboard.

For example, if I have my right CTRL key mapped to Windows on my local full-sized keyboard and press that, it will send the WIN scancode no matter what, be it remote desktop or Mouse without Borders - I press right CTRL on a machine without a keyboard connected and it pops up Start.

**Comment by sirtet** [comment]
I see.
Do you know another tool that would also work on input from remote?

**Comment by randyrants** [comment]
Sadly, I do not.  Microsoft Power Toys and AutoHotKeys both work off the local keyboard, so the remote session won't see it unless you've remapped the key locally.
