### ISSUE TITLE
SKLs?

### ISSUE THREAD

**Issue by apptum** [randyrants/sharpkeys#464]
Hey Randy, first: thank you! Awesome work, wonderful product! *happy!!

I use sharpkeys to change Windows' keys mostly for text editing like it's done on mac.
Now I was wondering: like you shared your crazy settings via SKL - do you know if there is already a collection of "typical" mapping situations / a collection of SKLs?

thanks again! :)

**Comment by randyrants** [comment]
Thanks!

For SKL's I don't know of any repository of files.  I mean, remapping keys is usually something to make an individual happy which I've always seen as a subjective thing.  I don't even know how many people use the feature :)

Except of course for turning off Caps Lock because that's universally hated.
