### ISSUE TITLE
Hot Keys not working even after disabling sharpkeys

### ISSUE THREAD

**Issue by Alden-Farias** [randyrants/sharpkeys#479]
I disabled " ` " key and it worked but it also disabled some hotkeys, For eg. if i pressed Fn + F10/F11 earlier it increased/decreased the volume respectively. But now it doesnt work. The F10/F11 and Fn keys are working properly when checked in a keybboard tester.
Then i removed the key mapping next day, but the hotkeys are still not working. Please help.

PS: I reinstalled keyboard drivers after removing key mapping.

**Comment by randyrants** [comment]
If you removed all of the mappings, saved it to the registry, and rebooted, the remapping is no longer there.  And to be clear, there is not "disabling SharpKeys" because the app doesn't have anything to do with the remapping: it edits a Registry Key that Windows uses to do the remapping.  You could set up a mapping, save it, uninstall the app, but when you reboot the machine, that remapping will kick in.

**Comment by randyrants** [comment]
What drivers are you referring to exactly, seeing as SharpKeys has no drivers of any kind.

Please re-read what I posted above, about what application is (and what it is not) and how it works.
