### ISSUE TITLE
UK pound key

### ISSUE THREAD

**Issue by kenmccallUK** [randyrants/sharpkeys#49]
Would it be possible to add the £ symbol to the standard mappings available?

(I have a US laptop keyboard with no NumPad.)

**Comment by randyrants** [comment]
What's the scan code value for a pound only symbol?  In so far as I know, the pound key only shows up on UK-based keyboards and then it's a combination key, like Shift+3 or Shift+4 or AltGr+4.  Since this registry key remaps the entire key, there's no way to map any of the above.

That said you can always us ALT+0163 (on the num keyboard) to inject a £ on a US keyboard.

**Comment by kenmccallUK** [comment]
Hi, 
Thanks for prompt response.  The UK pound on a UK keyboard replaces the # on US keyboard (ie Shift + 3). AFAICS there's no specific scan code for the pound - maybe it's done at some higher level in the driver or something??  (My laptop doesn't have a numeric keypad so I can't use the Alt+0163.)  Anyways, thanks for looking.
