### ISSUE TITLE
[Request] Display Off, Shut Down and Shortcuts with Multiple Key Assignments.

### ISSUE THREAD

**Issue by 000A000** [randyrants/sharpkeys#496]
**A)** I currently have to press `Fn + F6` to turn off the display on my Laptop. I want to just assign the `F6` key to **turn off display**, but this currently isn't an option. 
**B.i)** Assigning 'one button' to 'Power E0_5E' key doesn't do anything. Probably due to my Laptop (Acer) software not recognising that key function.
**B).ii)** Ideally, I would want to assign multiple keys (Example: `Right Shift + ? + : >`) to **shut down** my computer though. But I can't currently assign multiple keys to perform one action. 
|||
Q: Can I remap a combination of keys to one key?
A: Sadly, no. SharpKeys only remaps whole keys rather than a modified key. For example, you can remap Ctrl or C but you can't remap Ctrl+C to another key. That said, the Microsoft PowerToys tool does offer this functionality - you can learn more about their tool here: [Microsoft PowerToys](https://github.com/microsoft/PowerToys/releases).
https://github.com/randyrants/sharpkeys#additional-faq-and-answers
https://youtu.be/Gnr7bZQcEWU?t=493
|||
Note: Creating a shortcut via `C:\Windows\System32\shutdown.exe -s` and then assigning a shortcut path, doesn't work correctly on my Acer Laptop (Lenovo didn't have such issues). Windows10 always has CTRL + Alt as the default. Even after I assign something, it works the first time and then doesn't work anymore the next time. Also, I get this message (that I don't want):  _"You are about to be signed out windows 10 | Windows will Shutdown in Less than a Minute"_. Not sure where exactly Windows10 keeps its other shutdown files, so not `Shutdown.exe` located at: `C:\Windows\System32` or how to turn off that warning message (probably somewhere in Registry Editor).
£0.79 : Complete Shutdown | Apps · Utilities & tools · MKA Solutions

**C)** Willing to pay for a premium version of this product, if it can help address the issues posted here.
Currently I need **_[Microsoft PowerToys](https://github.com/microsoft/PowerToys/releases)_** (free but has lots of other stuff I don't need) & **_[Complete Shutdown](https://www.bing.com/ck/a?!&&p=94a53246f22be70aJmltdHM9MTY2NzQzMzYwMCZpZ3VpZD0yOGU2ZDgxNC02MDI1LTY5NTktMmYyMS1jYTQ1NjE5ZTY4NzYmaW5zaWQ9NTQ0MA&ptn=3&hsh=3&fclid=28e6d814-6025-6959-2f21-ca45619e6876&psq=microsoft+store+complete+shutdown&u=a1bXMtd2luZG93cy1zdG9yZTovL3BkcC8_UHJvZHVjdElkPTltd2o5bTZxdmpmMCZyZWZlcnJlcj1iaW5nd2Vic2VhcmNoJm9jaWQ9YmluZ3dlYnNlYXJjaA&ntb=1)_** (£0.79).

Side note: Microsoft Forums aren't very helpful, so not posting on there. 
I could have posted on the Acer forums, but I am currently using this software to help me change key assignments (I've used this software on two different laptop brands now). Hence, it's more helpful to post on here for all Windows OS users.

**Comment by randyrants** [comment]
B. I.) Power is a quirky key, like many of the hardware keys can be.  They are often intercepted by device and that never passes onto Windows, which means that Windows cannot remap it.

B. II. already has the explanation that covers all of the rest of the asks, because they're all the same ask: "Can I remap a modified key to be another key and/or a macro?"  Per the FAQ (and likely over 50 posts here) it's not supported by the Windows technology that SharpKeys is exposing: it's not a question of adding code or adding a new feature.  SharpKeys exposes a Registry Key that Windows uses to remap "whole" keys.

PowerToys or AutoHotKeys are the two programs I recommend for remapping like this.  They both offer an active key re-mapper which can do more things than the build in Windows remapping tech.

HTH!

**Comment by 000A000** [comment]
What about turning off the display screen (A)? Is that a hardware key too?

**Comment by randyrants** [comment]
It must be hardware: I know of no scancode for a "screen off" key.  I don't even know if the other products can help with that.

For the shutdown command, I type in some commands off the top of my head that might help the UX not pop up.  Try running shutdown /? since I haven't been on Windows 10 in a couple of years and the parameters could have changed on 11.

Beyond that, this is about the limit that I can help.  As you point out, this is not a Microsoft forum and my efforts here are scoped to SharpKeys (which cannot help with much of this.)
