### ISSUE TITLE
Support Expressive key

### ISSUE THREAD

**Issue by Tardymo** [randyrants/sharpkeys#498]
Would it be possible to add support for Expressive key on MS Designer Compact Keyboard? Currently app reports it as (E0_205B)
This key is configurable in MS Mouse and Keyboard Center, but the only options are "Expressive key", "Office key" or "Application key". I would like to remap it to Delete key.

**Comment by Tardymo** [comment]
Well, I read FAQ, and apparently this is a triple byte scancode, which is not remappable through Windows registry. In that case, if it is known, that such codes cannot be remapped, why doesn't sharpkeys say so? Instead it asks to check the website for updated version.

**Comment by randyrants** [comment]
The FAQ comes with the product, is on my blog, and this web site, so that's my attempt at education.  That the app itself doesn't shoot down triple-byte codes directly was something I toyed with but opted not to, especially if the remapping Registry were to ever change and/or for some people that claim to have had success on their systems.  e.g. they can remap AltGr successfully because they keyboard only has on triple-byte code.

PowerToys should be able to handle the emoticon key on the keyboard.
