### ISSUE TITLE
Cant handle Left Alt on Dell Precision 5560

### ISSUE THREAD

**Issue by dkjb634** [randyrants/sharpkeys#499]
I found Left Alt in the left list of keys, mapped it to Ctrl, but it doesn't work.
Tried handling the Left Alt via Type Key button, it just can't handle Left Alt, regrettably. (but handle Win, Ctrl, all keys fine)

**Comment by Tardymo** [comment]
There's a lot of useful information in  Readme section:

Q: Type a Key doesn't recognize the Alt key when I type it - how do I remap this key?
A: The Alt key scancode doesn't make it through the system, to get to the Type a Key window. Basically, when you type Alt, Windows sends it to the system menu and activate it, rather than sending the scancode to the window. You can still remap this key, but you'll see to select it from the list manually; you'll find it in the grouping of keys marked as "Special".

**Comment by DreymaR** [comment]
A bit more info on that: The left Alt key is special, indeed. It's used as a combo of a chording and sequencing modifier: Held down, it gives menu access when tapping corresponding letters; tapped, it gives menu access through a different method based on tap sequences (using the underlined letters in menu entries).

So the LAlt key is processed differently on KeyDown and KeyUp from how other keys and modifiers are. No wonder it doesn't show up like the others, then.
