### ISSUE TITLE
Pressed write to registry and now the Alt button doesn't work

### ISSUE THREAD

**Issue by caseysteffen** [randyrants/sharpkeys#507]
Hi Randy, working in windows 11. I can't seem to get the Alt button working anymore. I checked the regedit and there's no entry to delete, just the default. Any suggestions?

**Comment by randyrants** [comment]
Per the FAQ:
**Q: Type a Key doesn't recognize the Alt key when I type it - how do I remap this key?**
A: The Alt key scancode doesn't make it through the system, to get to the Type a Key window. Basically, when you type Alt, Windows sends it to the system menu and activate it, rather than sending the scancode to the window. You can still remap this key, but you'll see to select it from the list manually; you'll find it in the grouping of keys marked as "Special".
