### ISSUE TITLE
Can I remap Numpad button on ASUS laptops?

### ISSUE THREAD

**Issue by vroad** [randyrants/sharpkeys#514]
I attempted to turn off NumPad using SharpKeys, so that I don't accidentally turn on it but didn't work.

"Type key" button in SharpKeys recognizes NumPad button as `Special: € (E0_45)`, I remapped it to `Turn Key Off (00_00), however the button still works after writing changes to Registry and rebooting.

My laptop is Zenbook S Flip 13 OLED UP5302ZA. I've found a reddit comment from a user saying that NumPad can no longer be disabled on his ASUS laptop, does this mean that Microsoft made changes to Windows 11 that disables remapping?

**Comment by randyrants** [comment]
The mappings definitely work on Windows 11: there's been no functional change that I'm aware of and I've been using 11 going back about 2-3 years now, well ahead of the final release, disabling Caps Lock on every machine I touch.

In terms of Num Lock on a laptop, it's going to be iffy, just because it's usually an Fn key and that could have varied results.  I just looked for it on my Surface Pro keyboard, and it's not even offered as an option.  You might want to try selecting the explicit key from the list (look for Special: Num Lock, scancode 00_45) and see if that helps.

**Comment by vroad** [comment]
> You might want to try selecting the explicit key from the list (look for Special: Num Lock, scancode 00_45) and see if that helps.

Thanks, this worked. NumPad key got stuck once though, probably just because I disabled the key on SharpKeys while NumPad is still turned on. Has been working reliably after making sure that NumPad is turned off while configuring SharpKeys.
