### ISSUE TITLE
Remapping right shift to /?

### ISSUE THREAD

**Issue by SnowPrimate** [randyrants/sharpkeys#517]
Remapping right shift to /? (00_35) results in remapping to ;: (00_34)

Avell A52 HYB
Windows 11 Pro 22H2
OS build 22621.525

**Comment by jalescardoso** [comment]
same thing here

**Comment by randyrants** [comment]
Sorry for the delay in this but, I'm not able to reproduce this behavior.
![image](https://user-images.githubusercontent.com/18704482/223877742-a5d41976-59cb-4b04-8eb3-3baca593481f.png)

What keyboard layout are you using - I'm assuming it's not en-US?

**Comment by SnowPrimate** [comment]
hey Randy! Thanks for the response. Yes, it's not en-US. As far as I know it's Portuguese Brasil ABNT2 (I think it's a no dead keys)
![image](https://user-images.githubusercontent.com/6299375/224082325-3d4cc117-16e0-4c6f-8988-b9c6c250caa5.png)

**Comment by randyrants** [comment]
This... is going to be tricky.

The scan codes for all the keys are "language independent" meaning the : ; key on the pt-BR keyboard is the same scan code as the / ? key so it's doing what it's expected to do.  User presses the 00_35 key and the keyboard language layout decides what to send to the screen, / ? for en-US and ; : for pt-BR.

So, now the question is: where is the / ? key on the pt-BR keyboard and what's its scan code?  As near as I can tell, I don't think there is one - to get these symbols, it looks like it's ALTGR+Q for / and ALTGR+W for ? which means SharpKeys won't be able to help since it cannot remap to a combo key.

That said, there's are other options: PowerToy and AutoHotKeys should be able to map Right SHIFT to one of those combo keys - you'd need another key for the other character.

Sorry the Windows remapping tech isn't of more help here!

**Comment by SnowPrimate** [comment]
Hey Randy! sorry, the one above is a modified version for that specific notebook. If I plug a keyboard to the notebook it does the /? key as it should. The original Portuguese Brasil ABNT2 is the following:

![image](https://user-images.githubusercontent.com/6299375/224111324-3cb2e939-cfe6-4586-9118-c825656c6e57.png)

**Comment by randyrants** [comment]
I was basing my comments more on this layout: https://learn.microsoft.com/en-us/globalization/keyboards/kbdbr_2 rather than the actual picture :)

**Comment by SnowPrimate** [comment]
Ohhh thanks! I just found this out. Would it be 00_73?
![image](https://user-images.githubusercontent.com/6299375/224123698-dd76aba8-6289-4f5e-9b57-9547b797c242.png)

**Comment by SnowPrimate** [comment]
yaaay it did work!

**Comment by randyrants** [comment]
Bingo :)
