### ISSUE TITLE
When binding Vertical Bar it doesn't work (00_2B)

### ISSUE THREAD

**Issue by CainDev** [randyrants/sharpkeys#519]
When remapping my key to Vertical Bar and Backslash it doesn't give me the Vertical Bar.

Currently its 
Standard Press: #
Shift Press: ~
Alt Press: \

Can someone help explain this to me? I'm a developer myself and my keyboard doesn't have a Vertical bar and I kinda need it 😭

https://i.imgur.com/Pi6zsZI.png

**Comment by randyrants** [comment]
If I had to guess, you're on a non-US keyboard?  This is where things get tricky because the app only knows the scan codes and calls out the keys with en-US labels; this is why I added Type Key, for other regions.

Two suggestions: try remapping the PgDn key to ` ~ (00_29) because the ALT key of that should give you a |.  If that doesn't work give PowerToys a try.  Since that's a more active remapping tool, it might let you remap to a specific character regardless of regional keyboard layout.

**Comment by CainDev** [comment]
Unfortunately when binding it to 00_29 I just get [`] and [¬]

I'll look into Microsoft PowerToys to see if it can help me, thanks.

**Comment by DreymaR** [comment]
The best solution for such needs is to use software. My EPKL program may seem like overkill for such a simple need, but then again as a developer maybe you want some other solutions it offers too? But then again, you may be on Linux. Then again again, the vertical bar is readily available on Linux layouts and certainly with the Compose method.

As Randy correctly points out, what glyphs you get from a key press is not a keyboard thing but an OS/software thing.

If you're interested, take a look at EPKL. It's big but powerful:
https://github.com/DreymaR/BigBagKbdTrixPKL

**Comment by randyrants** [comment]
> Unfortunately when binding it to 00_29 I just get [`] and [¬]
For non-modified and SHIFT, that makes sense.  What about ALTGR+` - that should yield a | per https://www.uk-yankee.com/sites/default/files/800px-kb_united_kingdom_svg.png
