### ISSUE TITLE
doesnt delete instructins after uninstall

### ISSUE THREAD

**Issue by star-morninglight** [randyrants/sharpkeys#520]
basically , i deleted the program from the control panel but when i installed it again the instructions i gave it are still saved (i was switched shift with caps lock)
for what its worth, i got a sharpkeys.zip from softonic's website that only had an .exe in it, which immediatly worked with no install path and no uninstall which might be what caused this (i deleted said .exe)
 
all i know so far is that theres no trace of the program on any of my harddrives but when i uninstall it and install it again, it keeps the instructions from the last time

**Comment by randyrants** [comment]
That would be because the app itself doesn't do the remapping itself: it is a front end to a Registry Key that Windows uses to remap the keys.  Since users can edit the Registry on their own - without SharpKeys - there's no way the installer would know to clear settings out as it uninstalled.  In fact, the app is a single EXE, users don't even need to run the installer, much less the uninstaller.  Drop the EXE on a PC, set up the keys you want, and then delete the app; the only runtime needed is the .NET Framework, which would be with Windows anyway.  No way I'm telling the uninstalled to remove values that SharpKeys may or may not have recorded, because that would be disastrous for some.

Ultimately, this is by design.  If you wanted to remove any existing mappings, open SharpKeys, Delete All. save the changes to the Registry, and reboot.

**Comment by star-morninglight** [comment]
thanks for the response!
