### ISSUE TITLE
Changing/removing keys if 'just me' is selected on install via other user

### ISSUE THREAD

**Issue by gangstilla** [randyrants/sharpkeys#521]
Hi,

So the other week I installed Sharpkeys on my boss's PC. And as a prank, I tried to swap the keys of 1 and 2.
What I ended up doing, which was my fault, is swapping 1 to 2, and 2 was still 2. So he couldn't type in his password which needed both keys to work.
Viewing sharpkeys from another account also did not allow us to view the modified registry keys.
We tried removing the registry key and rebooting and it didn't work to solve the issue.
However I emulated this issue on my PC and it seemed to be fixable with the deletion of the registry key.
Anyways, we had to do a 'full registry fix' in order to solve the issue.

Is this intended with the 'just me' installation option? I did take a look at other issues raised but did not seem to work here.

Thanks if you do look at this.

**Comment by DreymaR** [comment]
Registry remaps are global or by-user. But I believe SharpKeys only uses the global version.

However, depending on your setup you may have registry settings by-user anyway. Which indeed would make it impossible to see the changes you did on your boss' account from another account – unless that other account were admin and you looked in the right place (wherever that may be).

One thought: Couldn't your boss log on with the on-screen keyboard? And then, re-running SharpKeys logged on as the boss you should be able to see and remove the changes you did.

**Comment by gangstilla** [comment]
@DreymaR We tried on screen keyboard and that didn't work, it kept the current setup still, I am told and hence we couldn't see the changes because we couldn't get onto the account.
The other account was admin and we couldn't see anything from that.

**Comment by randyrants** [comment]
I don't see that there is anything to look for in this.

- There is no "per user" setting that's available for mapping keys.  The only Registry Key that does the remapping lives under HKEY_LOCAL_MACHINE; putting it under HKEY_CURRENT_USER does nothing.
- Removing the Scancode Map value or the entire Keyboard Layout Key in the Registry and rebooting will work.  It must work because once Windows reboots, it has no instructions about how to remap keys.  It's like saying that Windows spontaneously decided on its own to hold onto the remapping without instructions: either the key was restored by some process on the power down or the box was suspended, rather than rebooted.
- Running SharpKeys from another account on the box would work, if the account has Administrator permissions.  Again, the remapping entry is exclusive to HKLM which by its very nature _should_ be visible to all users but requires admin rights to do so.  Or your company has some sort of add on masking that DreymaR has mentioned above, like a group policy or something.  Not a thing can be done for that, as it's organizational specific.
- Lastly, if this wasn't working with the onscreen keyboard, I have no idea what has happened: for years, I've used the On-Screen Keyboard and just confirmed that it's oblivious of the Windows remappng since it blissfully just turned-on caps lock, which is disabled on the physical keyboard.  Same thing applies to the touch screen keyboard, if you have it enabled/available.
- Bonus: Remote desktop may have worked as I have seen strange things happen with some of my laptop keys that are remapped locally but behave differently when they go into a remote window.  For example, my local Surface has Home mapped to F9 and F9 mapped to Home, which helps me to flip the state of Fn-Lock.  When I'm local, it acts like Home; when I'm in a remote session it acts like F9.  No sure if this is a side effect of Fn or that Remote Desktop ignores the locally remapped keys.  Since I have Caps Lock disabled everywhere, local and remote, I never would have noticed this until recently.

Nothing much that I can do about any of the above: no amount of my code is going to save the day, but I also wonder if you tried this from the FAQ:
**Q: I have accidentally remapped a key I need to sign in with but I can reboot to safe mode or WinPE and get to a CMD prompt. Can I reset the mappings?** 
A: If you can get to a CMD window. you should be able to open regedit, which will prompt for Administrator rights. Navigate to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout, delete the Scancode Map value; likewise, if you have an admin CMD prompt open already, you can remove the Registry value by running: reg delete "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout" /v "Scancode Map" Reboot after resetting the Registry value.
