### ISSUE TITLE
trying to remap Right-alt in Hebrew and Error!

### ISSUE THREAD

**Issue by Iftachdekel** [randyrants/sharpkeys#533]
hey, thanks for this app,
having a problem in Hebrew
when  i trying to remap Right-Alt (E0_2038) it said that SharpKeys doesnt Know about this key,,,
help?

**Comment by DreymaR** [comment]
Try (E0_0038).

**Comment by randyrants** [comment]
Hi,

The key you are trying to remap isn't Right Alt: E0_2038 is Alt+Gr which is not remappable with SharpKeys because it's a triple-byte scancode.  From the FAQ:

**Q: Type a Key shows a code that is E0_nnnn - can I remap this key?
Q: Type a Key for AltGr shows a code that is E0_2038 - can I remap this key?**
A: If a scancode has 6 characters, then it is what is known as a triple-byte scancode which is something that cannot be remapped by the Windows Registry. To remap a key like this, you'll need an active remapper like Microsoft PowerToys or AutoHotKeys or the app that came with the keyboard (e.g. Logitech's Options) if available.

**Comment by DreymaR** [comment]
Yes, yes, but...

Why doesn't the FAQ suggest to try the Right Alt (E0_0038) manually instead, in this particular case? You know I use that and it works perfectly for me.

Somehow, Microsoft got over the issue of needing Left Ctrl _plus_ Right Alt for AltGr, and interprets an RAlt key press as AltGr for any layout DLL that uses an AltGr key (configurable in MSKLC).
