### ISSUE TITLE
"Alt" key is not recognized

### ISSUE THREAD

**Issue by YuriLeivas** [randyrants/sharpkeys#537]
I have a kumara abnt2 keyboard. In the application, the "Alt" key, which is on the left side of the space key, is not recognized. I tried using "Special: Left Alt (00_38)" but that didn't work either.

**Comment by randyrants** [comment]
From the FAQ:
**Q: Type a Key doesn't recognize the Alt key when I type it - how do I remap this key?**
A: The Alt key scancode doesn't make it through the system, to get to the Type a Key window. Basically, when you type Alt, Windows sends it to the system menu and activate it, rather than sending the scancode to the window. You can still remap this key, but you'll see to select it from the list manually; you'll find it in the grouping of keys marked as "Special".

If you remap that, save your settings, and reboot and it still doesn't work, you may have an AltGR key which is not supported.
