### ISSUE TITLE
Screen brightness control button

### ISSUE THREAD

**Issue by Gapehorn1** [randyrants/sharpkeys#548]
It would be nice if I could be able to change F6 to lower the screen brightness, and F7 to raise it up. Idk just a suggestion.

**Comment by DreymaR** [comment]
I don't think there is a standard scan code for Screen Brightness keys? They're not among the "Web" nor "Media" keys ttbomk.

When laptops do have these keys on Fn plus a F# key, I suspect that it's handled by a proprietary keyboard driver, via another key code. I'm not sure, but that could be the case.

You could try searching for how Brightness keys are handled, because I'm not sure.

**Comment by randyrants** [comment]
DreymaR is correct: there is no Windows scancode that can be remapped for brightness control.
