### ISSUE TITLE
Eject button

### ISSUE THREAD

**Issue by Nifir** [randyrants/sharpkeys#550]
![Magic-Keyboard-900x0-c-default](https://github.com/randyrants/sharpkeys/assets/35903335/bc274a13-fe95-45ee-86c6-f0cce9bbb8d8)
Hi, is there any option to map the Eject Button to any key? If I'm not wrong this button should have the number 0xC000000b8. I couldn't find this number in SharpKeys so I tried to add it manually but I failed. :(

**Comment by Nifir** [comment]
I added it manually but with no success. 
![Zrzut ekranu 2023-10-31 213720](https://github.com/randyrants/sharpkeys/assets/35903335/87aa9f0c-16d6-4ddd-b77d-ee1a89efaba4)

**Comment by verityj** [comment]
Same here! I figured out how to remap that Eject key (0xC000000b8) on a mac, but I'm having no luck on Windows.

https://verityj.github.io/2023/06/17/eject.html

**Comment by DreymaR** [comment]
The registry remapping method that SharpKeys uses (but which is really a part of Windows) remaps two-byte scan codes to each other. So any keys not fitting that description, including your Eject key, is not remappable by that method.

This is very clearly stated in the SharpKeys documentation, by the way. But hey, that's a gutsy attempt! :-)

**Comment by verityj** [comment]
> The registry remapping method that SharpKeys uses (but which is really a part of Windows) remaps two-byte scan codes to each other. So any keys not fitting that description, including your Eject key, is not remappable by that method.
> 
> This is very clearly stated in the SharpKeys documentation, by the way. But hey, that's a gutsy attempt! 😎

All righty, time to stop thinking about it :) In my defense, I have no idea what "two-byte scan codes" are as opposed to the others, as this is all just a self-learning journey. Thanks for explaining!

**Comment by DreymaR** [comment]
See how all the remappable keys have their most significant byte as 00 or E0? The E0 is a special case that distinguishes, say, Right Alt from Left Alt when there are two versions of a key. But otherwise, that byte is empty. So the scan code itself is just one byte.

That's all there is to it really. The Windows key remap is based on one-byte scan codes. Any special keys that send more than one byte, are not remappable by this method. It's not really a feature of SharpKeys but of Windows itself.
