### ISSUE TITLE
Doesn't recoignize the LEFT ALT of Logitech MX keys 

### ISSUE THREAD

**Issue by K2adir** [randyrants/sharpkeys#570]
the latest version doesn't recognize the left alt key(left of the space bar). Type KEY doesn't work either. Selecting it from the list of keys do not work.

**Comment by randyrants** [comment]
Not sure what your config looks like, but it should work.  In fact, I often remap this key myself.  Per the FAQ, Type Key doesn't work with ALT keys because Windows traps the key and doesn't send it to the window, but you can select it under the "Special" section.

If you have the mapping configured and rebooted after saving it, it could be the Logitech MX keyboard is not sending the code key it's advertising, especially since I think that keyboard is one of the Mac + Windows combination deals.

**Comment by K2adir** [comment]
> Not sure what your config looks like, but it should work. In fact, I often remap this key myself. Per the FAQ, Type Key doesn't work with ALT keys because Windows traps the key and doesn't send it to the window, but you can select it under the "Special" section.
> 
> If you have the mapping configured and rebooted after saving it, it could be the Logitech MX keyboard is not sending the code key it's advertising, especially since I think that keyboard is one of the Mac + Windows combination deals.

It was a fresh install, and I think you are right. Since MX is a MAC/WIN combo keyboard, maybe it's doing some fancy things behind the scenes.
