### ISSUE TITLE
Sleep and Play/Pause remaps not working under Win10

### ISSUE THREAD

**Issue by nooborka** [randyrants/sharpkeys#68]
Hello!
I have remapped the Scroll Lock key to Sleep and the Pause/Break key to Play/Pause media, but none of them is working. If I remap them to something else, like 'G', it is working fine. Do you have any idea why this is happening? I suspect windows might detect that my PS/2 keyboard does not have these extended keys and might not even listen for them... Or it's not how this works?
Thanks, nooborka

**Comment by randyrants** [comment]
Few comments:

Pause/Break may not be remappable on some keyboards because they have a hardware component to them.  Also, I've seen weirdness where keys called ScrLk aren't Scroll Lock so that may also not be remappable.  Likewise, Play/Pause is also something that might not be supported because it really depends on what's listening for that command on the Windows box itself.  If it is successfully remapping to G, then the app is doing what 's supposed to do but all of these special keys are being weird on your keyboard and/or PC.

HTH!
