### ISSUE TITLE
Mapping for a split spacebar?

### ISSUE THREAD

**Issue by Techgeekster** [randyrants/sharpkeys#69]
Is there a way to map the left and right side of a split spacebar?
When I hit 'Type Key' and I enter the left side it comes up the same as the right side.  I want to just disable one side.

**Comment by randyrants** [comment]
If you're getting the same command with both halves, it's because that's what Windows is seeing it as.  Since I don't know of any scan code that splits the space bar, there is likely a driver that is offering different functionality between the two buttons before Windows gets notified the key is pressed.
