### ISSUE TITLE
'E0_5B' -> '00_1D'  mapping won't work from mac to win under RDP

### ISSUE THREAD

**Issue by avishnyakov** [randyrants/sharpkeys#74]
Hey guys, 

Using sharpkeys with the following config:
* mac running VirtualBox
* windows 2016 under VirtualBox
* RDP connection, via Microsoft Remote Desktop, from mac to win VM being under Virtual Box

Trying to remap left win to left CTRL  ('00_1D' -> 'E0_5B'). sharpkeys does identify while setting keys in the settings but reboot won't do anything. Keys aren't mapped.

Pretty much, I've got the same case as these guys do but I can't get it working
> Not only did I have to map CTRL over to the Windows key ('00_1D' -> 'E0_5B'), but I had to do the reverse mapping too ('E0_5B' -> '00_1D').
> https://forums.virtualbox.org/viewtopic.php?f=8&t=37931

Pure connection via VirtualBox works well. RDP from mac to win, however, won't work - keep passing win key all the time.

Is it some limitation of sharpkeys or specific setup of mac/win/virtual box?

**Comment by randyrants** [comment]
There's so many layers of interpretation going on, I couldn't begin to image who is intercepting and changing scancodes.  As I recall, most VM clients do weird things with CTRL and ALT because they use them to do remote or local commands instead of just passing along the keypress.

I would select whatever characters you want to remap from lists - rather than Type Key - and even then, I would test it on a throwaway VM.  It's very possible that this will prevent regular operations with the remote client.

**Comment by avishnyakov** [comment]
@randyrants , agree. Tried a few other RDP managers to get it working. Extremely inconsistent behaviour. I would not focus on this ticket at all, that's a rabbit hole.

I would close this suggesting using other RDP managers, try various combination unless it would work for your specific case.
