### ISSUE TITLE
Unable to rebind Pause/Break key

### ISSUE THREAD

**Issue by shezdogga** [randyrants/sharpkeys#87]
I've tried rebinding my pause/break key (00_45) to Media: Next Track (E0_19) which instead of rebinding the  pause/break key, it rebinds the numlock key. (US Layout keyboard)

**Comment by randyrants** [comment]
That would be because the scancode for NumLock is 00_45.  Pause/Break is a triple byte scancode which is incredibly hard to remap successfully and even still, it's often a key that is intercepted by the hardware so it may not even get to Windows.  That your keyboard is sending that scancode when you use Pause/Break makes me wonder if you have a Fn combo that you're supposed to be pressing, but I'm not sure.

**Comment by shezdogga** [comment]
For me the function key is only used for changing backlighting, it is not used for anything else
