### ISSUE TITLE
Installed windows updates, mapping refuses to stick

### ISSUE THREAD

**Issue by jvilhuber** [randyrants/sharpkeys#97]
Today, I installed a bunch of updates, and my mapping (just mapping caps-lock to ctrl-left) stopped working. Trying to set it with even the latest sharpkeys refuses to work (I was using 3.5, but installed 3.6.0 in the hopes it would fix it). Happy to provide any logs or debugs, if someone can give me instructions (I'm not a windows guy).

Packages installed were:
```
PS C:\WINDOWS\system32> Get-WindowsPackage -Online | ?{ $_.InstallTime -gt [datetime]::now.AddDays(-15) }

PackageName  : Package_for_KB4093110~31bf3856ad364e35~amd64~~10.0.1.0
PackageState : Installed
ReleaseType  : SecurityUpdate
InstallTime  : 5/7/2018 3:25:00 PM

PackageName  : Package_for_KB4093432~31bf3856ad364e35~amd64~~10.0.1.0
PackageState : Installed
ReleaseType  : Update
InstallTime  : 5/7/2018 3:25:00 PM

PackageName  : Package_for_RollupFix~31bf3856ad364e35~amd64~~15063.1058.1.6
PackageState : Installed
ReleaseType  : Update
InstallTime  : 5/7/2018 4:34:00 PM

```

**Comment by randyrants** [comment]
Well, the remapping is done by Windows and I'm running the most recently released build (1803) so I'm not sure what would be impacting this suddenly.  Are you still seeing the remapped keys in SharpKeys when you look after a reboot?  If that's the case, the registry is staying as it should be; if it's not maybe there is a group policy that's causing issues the registry to be reset?  

Not entirely sure what the issue is here.

**Comment by jvilhuber** [comment]
I noticed that, using regedit, I can see the mapping for a brief period of time in the registry, and then it magically disappears (even before a reboot). Something appears to be removing the mappings after they are inserted.
So this is unlikely to be a problem with SharpKeys, but I'm so far at a loss as to what could be deleting the registry entry.
