### ISSUE TITLE
Clarification on using SharpKeys 36

### ISSUE THREAD

**Issue by githmw** [randyrants/sharpkeys#99]
I just downloaded sharpkeys36.zip, and I have a few questions which your FAQ does not address. My OS is Windows 7 (64 bit) Pro, SP1.

I downloaded the .zip file to a USB stick, and unzipped it there. Selecting SharpKeys.exe brinks up the User Account Control screen. After selecting Yes, the program opens on my computer. The Type Key function works just fine. I have not gone any farther, until I get a few questions answered.

1. Will I be able to write to Register with the installation on the USB stick, or do I have to install SharpKeys on one of my computer hard drives?

2. Once I "Write to Registry", can I ever delete it, and fall back to the standard Windows mapping? If so, how do I do this?

3. It is not clear to me exactly what the "Delete All" option does.

4. Can I have saved more than one mapping, and switch between them?

Thanks,

Harry

**Comment by randyrants** [comment]
1. Running from a USB stick shouldn't be a problem.  UAC has to fire so SharpKeys can read/write to the Registry so that's normal.

2. Yes: using Delete All and then Write to Registry will remove all of the remappings on the reboot.

3. See #2 

4. Not with this tool.  You can always export the Registry key and use the resulting .REG files to swap back and forth but know that you have to reboot with each change.
